### ISSUE TITLE
xmlsec1-1.2.24 doesn't link against openssl-1.0.X on windows

### ISSUE THREAD

**Issue by mitchblank** [lsh123/xmlsec#107]
For a long time, libcrypto on windows was called libeay32 (for weird legacy reasons)  I guess they changed that to libcrypto finally in 1.1.X to be consistent with the UNIX naming.

At one point xmlsec1's windows build seemed to have code to deal with this naming difference between 1.0.x and 1.1.x, but that was removed in 1.2.24:
https://github.com/lsh123/xmlsec/commit/c34820439a3254b2d42711a208f0e21fc23bf672#diff-56b87a9bb82dd6809096684a0db830ffL398

Was that intentional?  I am able to compile against 1.0.2k on several UNIX platforms, but on windows I get an error:

```
LINK : fatal error LNK1181: cannot open input file 'libcrypto.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe"' : return code '0x49d'
```

I'm going to try locally patching it and see if that works (I don't have an interactive build environment handy so I'll have to submit a patch to our batch build system, so I won't have an answer right away.)

**Comment by lsh123** [comment]
It actually compiled but failed to link :) Yes you are correct. This change is a mistake. I'll think how to do it better since I really want to have OpenSSL version detection done at compile time (vs config time).

**Comment by mitchblank** [comment]
Yeah it's tricky on windows unfortunately.  I'm sure it's possible by finding which library name appears first in the lib path in `configure.js` or something?

Anyway, I can confirm that just replacing `libcrypto.lib` with `libeay32.lib` on those two lines let me compile.

**Comment by lsh123** [comment]
Restored the old user-config for openssl on win32: https://github.com/lsh123/xmlsec/pull/109
