### ISSUE TITLE
Verification success and error, two xml files with same content, one is formatted one is flatten

### ISSUE THREAD

**Issue by bovetliu** [lsh123/xmlsec#108]
Recently I did one example to test xml "sign and verify".
I prepared two xml files. One is a formatted SAML logout response. One is the flattened version of the previous file. The formatted version of the SAML logout response file (The xml file to be signed) is

```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://localhost:8443/saml/ls/" ID="_271dd592d53941d6bd8209a0d22be2d0" InResponseTo="id-r9kqbQmiYfiHaH16K" IssueInstant="2017-04-29T01:25:36Z" Version="2.0">
   <saml:Issuer>http://somecorp.com/saml-idp/4qixg2okec0wuzc8/metadata/</saml:Issuer>
   <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
      <ds:SignedInfo>
         <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
         <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
         <ds:Reference URI="#_271dd592d53941d6bd8209a0d22be2d0">
            <ds:Transforms>
               <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
               <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
            <ds:DigestValue />
         </ds:Reference>
      </ds:SignedInfo>
      <ds:SignatureValue />
      <ds:KeyInfo>
         <ds:X509Data>
            <ds:X509Certificate />
         </ds:X509Data>
      </ds:KeyInfo>
   </ds:Signature>
   <samlp:Status>
      <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
   </samlp:Status>
</samlp:LogoutResponse>
```

Then I run following bash commands:
```bash
#!/bin/sh

#following two can be used by IDP to sign the logout response
xmlsec1 --sign --privkey-pem ./domain.key,./domain.crt --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:LogoutResponse --output logout_signed.xml logout_to_sign.xml

xmlsec1 --sign --privkey-pem ./domain.key,./domain.crt --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:LogoutResponse --output logout_signed_flatten.xml logout_to_sign_flatten.xml

#following two can be used by SP to verify the logout response
xmlsec1 --verify --pubkey-cert-pem ./domain.crt --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:LogoutResponse --store-signatures --node-id _271dd592d53941d6bd8209a0d22be2d0 --output ./logout_verified.xml logout_signed.xml

xmlsec1 --verify --pubkey-cert-pem ./domain.crt --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:LogoutResponse --store-signatures --node-id _271dd592d53941d6bd8209a0d22be2d0 --output ./logout_verified_flatten.xml logout_to_sign_flatten.xml
```
What makes me confusing is the result. **The first verification result is an OK while the latter one is a failure.**

I have uploaded [all related files](https://drive.google.com/file/d/0BxJHBzr08_eBWmJXbnRqTG1nbkU/view) into google drive. You might click the link the download

Thanks for your help in advance.

**Comment by lsh123** [comment]
The second command tries to verify the *template* logout_to_sign_flatten.xml instead of the signed file logout_to_sign_flatten.xml

xmlsec1 --verify --pubkey-cert-pem ./domain.crt --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:LogoutResponse --store-signatures --node-id _271dd592d53941d6bd8209a0d22be2d0 --output ./logout_verified_flatten.xml logout_to_sign_flatten.xml

**Comment by bovetliu** [comment]
Thank you for pointing out the problem. Sorry about my fault.  I would like to ask one additional question. I am trying to integrate SAML authentication into my project. When I received response from IDP after Log-in attempt, my application is able to successfully verify the response. However, when I received the LogoutResponse, my application is unable to verify it.  xmlsec1 says 

> invalid data:data and digest do not match

You can find all related files in[ the link](https://drive.google.com/open?id=0BxJHBzr08_eBSDd3enFZMzRGNG8)

Thank you very much

**Comment by lsh123** [comment]
That's something you will have to debug yourself -- the digest doesn't match and I can't tell you "why". However, in my experience it is usually related to c14n process. Use --store-references command line option to save/print the pre-digest buffer right before digest is calculated by xmlsec1 utility and it might give you a clue as well.

**Comment by bovetliu** [comment]
Hi Aleksey, Thank you for insightful suggestion. I indeed found that the pre-digest buffer is different from original xml(`tmpevq9o4gf.xml`) file with `<ds: Signature>` node removed.  
You mentioned this could be c14n process.
I checked https://www.w3.org/TR/xmldsig-core/#sec-DigestMethod
> **3.1.1 Reference Generation**
> .....
> If the data object is a node-set and the next transform requires octets, the signature application MUST attempt to convert the node-set to an octet stream using Canonical XML

This means the node with ID="_76851c2da7f34e89b09f2b703f818edf" is stringified differently using c14n. SAML IDP  and service provider generated different octete streams of the same XML node.   

Since they are using different results of Reference Generation, they calculated different digest value, and correspondingly different signature value. Is my understanding correct?

**Comment by lsh123** [comment]
The signature node is excluded because its content changes during the process (e.g. digest and signature values). You need to compare the pre-digest buffers from both signature and verification processes.

**Comment by bovetliu** [comment]
Hi Aleksey, I understand your meaning.  Here is my thought.
The original pre-digest buffer output, the digest value is `qg99uz2j6amFkJTVOT3nQ2tcLog=`, which does not match digest value calculated by Identity Provider 
```xml
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://localhost:8443/saml/ls/" ID="_76851c2da7f34e89b09f2b703f818edf" InResponseTo="id-FQgf1wgjA6bzWTtGZ" IssueInstant="2017-04-28T19:08:17Z" Version="2.0"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">http://fac.corp.fortinet.com/saml-idp/4qixg2okec0wuzc8/metadata/</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"></samlp:StatusCode></samlp:Status></samlp:LogoutResponse>
```
The formatted pre-digest buffer output 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://localhost:8443/saml/ls/" ID="_76851c2da7f34e89b09f2b703f818edf" InResponseTo="id-FQgf1wgjA6bzWTtGZ" IssueInstant="2017-04-28T19:08:17Z" Version="2.0">
    <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">http://fac.corp.fortinet.com/saml-idp/4qixg2okec0wuzc8/metadata/</saml:Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
</samlp:LogoutResponse>
```

The original LogoutResponse with `<Signature>` node removed, the digest value is `CmTRGAtAWieezJVWspfREw4O+xQ=`. **which matches the digest value calculated by Identity Provider.**
```xml
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://localhost:8443/saml/ls/" ID="_76851c2da7f34e89b09f2b703f818edf" InResponseTo="id-FQgf1wgjA6bzWTtGZ" IssueInstant="2017-04-28T19:08:17Z" Version="2.0"><saml:Issuer>http://fac.corp.fortinet.com/saml-idp/4qixg2okec0wuzc8/metadata/</saml:Issuer><samlp:Status><samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"></samlp:StatusCode></samlp:Status></samlp:LogoutResponse>
```
The formatted LogoutResponse with `<Signature>` node removed
```xml
<?xml version="1.0" encoding="UTF-8"?>
<samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Destination="https://localhost:8443/saml/ls/" ID="_76851c2da7f34e89b09f2b703f818edf" InResponseTo="id-FQgf1wgjA6bzWTtGZ" IssueInstant="2017-04-28T19:08:17Z" Version="2.0">
    <saml:Issuer>http://fac.corp.fortinet.com/saml-idp/4qixg2okec0wuzc8/metadata/</saml:Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
    </samlp:Status>
</samlp:LogoutResponse>
```
So this means service provider(my project), and identity provider are using different results of Reference Generation (c14n process) to calculate digest value, which surely will not match. 
Is my understanding correct? 
Thanks

**Comment by lsh123** [comment]
Correct.
