### ISSUE TITLE
gcrypt memory leak

### ISSUE THREAD

**Issue by w5678912345** [lsh123/xmlsec#113]
in code "src/gcrypt/kw_aes.c"

function:
1. xmlSecGCryptKWAesBlockDecrypt
2. xmlSecGCryptKWAesBlockEncrypt 

you use libgcrypt funtion but not close.

    err = gcry_cipher_setkey(cipherCtx,
                             xmlSecBufferGetData(&ctx->keyBuffer),
                             xmlSecBufferGetSize(&ctx->keyBuffer));
    if(err != GPG_ERR_NO_ERROR) {
        xmlSecGCryptError("gcry_cipher_setkey", err, NULL);
        return(-1);
    }

    /* use zero IV and CBC mode to ensure we get result as-is */
    err = gcry_cipher_setiv(cipherCtx, g_zero_iv, sizeof(g_zero_iv));
    if(err != GPG_ERR_NO_ERROR) {
        xmlSecGCryptError("gcry_cipher_setiv", err, NULL);
        return(-1);
    }

why not use "gcry_cipher_close(cipherCtx);" to close "cipherCtx" when err.

sorry, my english is bad.

**Comment by lsh123** [comment]
yes you are correct, I'll fix it shortly.

**Comment by lsh123** [comment]
Fixed.
