### ISSUE TITLE
Installing latest version on RHEL

### ISSUE THREAD

**Issue by zshauli** [lsh123/xmlsec#120]
I'm trying to install the latest library version (1.2.24) on RHEL 7.2, in order to support the "dm.xmlsec.binding" python package.
When trying to run "yum install xmlsec1-devel" I get version 1.2.18, which dm.xmlsec.binding is not compatible with.

What are my options for installing the latest version on Redhat? Is there a ready-made RPM for it? Is there a repo I can ask yum to download the package from?

**Comment by lsh123** [comment]
I think you should ask this question to Redhat support :)
