### ISSUE TITLE
nested signatures issue: I can't sign a XML file that contains another already signed XML 

### ISSUE THREAD

**Issue by degzcs** [lsh123/xmlsec#124]
Hi, 
I'm trying to sign a X509 document which has nested another already signed XML. But when I try to sing it, XMLsec try to sign again that document and show the next error:

```sh
func=xmlSecXPathDataExecute:file=xpath.c:line=240:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('THIS_IS_THE_ID_FROM_THE_NESTED_XML')); xml error: 0: NULL\nfunc=xmlSecXPathDataListExecute:file=xpath.c:line=323:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: \nfunc=xmlSecTransformXPathExecute:file=xpath.c:line=424:obj=xpointer:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: \nfunc=xmlSecTransformDefaultPushXml:file=transforms.c:line=2101:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed: \nfunc=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1037:obj=xpointer:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: \nfunc=xmlSecTransformCtxExecute:file=transforms.c:line=1084:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: \nfunc=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1405:obj=unknown:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed: \nfunc=xmlSecDSigCtxProcessReferences:file=xmldsig.c:line=750:obj=Reference:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed: \nfunc=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=512:obj=unknown:subj=xmlSecDSigCtxProcessReferences:error=1:xmlsec library function failed: \nfunc=xmlSecDSigCtxSign:file=xmldsig.c:line=286:obj=unknown:subj=xmlSecDSigCtxSignatureProcessNode:error=1:xmlsec library function failed: \nError: signature failed \nError: failed to sign file \"/tmp/unsigned-1500451577.xml20170719-27170-17osfvm\"\n
```   

as you can see in this part: 
` function failed:expr=xpointer(id('THIS_IS_THE_ID)_FROM_THE_NESTED_XML'))`
seems that the library is trying to sign the XML that was already signed.

The solutions that I tried were:
1. use the DTD to specify the ID as recommend in the documentation [here](https://www.aleksey.com/xmlsec/faq.html) in section 3.2. I got two different errors. 
1.1 if I specify just the ID that I want to I got the same error above.
```xml
<!DOCTYPE something [
            <!ATTLIST outsidetagname ID ID #IMPLIED>
          ]>
```
1.2 If I specify both IDs the document is not signed but I got an error but not a description 
```xml
<!DOCTYPE something [
            <!ATTLIST insidetagname ID ID #IMPLIED>
            <!ATTLIST outsidetagname ID ID #IMPLIED>
          ]>
```
2. sing the `--node-xpath` option and the solution 1.2 together, I got this error:
`Segmentation fault (core dumped)`

I appreciate any help from you.

Thanks

**Comment by lsh123** [comment]
Please attach the example file to reproduce the problem.

**Comment by lsh123** [comment]
The xmlsec command line tool will try to sign the first Signature element it finds. If you want to sign the second signature, you need to point xmlsec to it. The simplest option is to specify id or xpath (--node-id or --node-xpath). See https://www.aleksey.com/xmlsec/xmlsec-man.html for more details.

**Comment by degzcs** [comment]
As I mentioned in the first message I already try to use `--node-xpath '/FirstXml'` but I  got errors. Could you please tell me with my example to which exactly node I have to point?

Thanks!

**Comment by lsh123** [comment]
The easiest way is to use Ids:

<Signature Id="SecondSignature" xmlns="http://www.w3.org/2000/09/xmldsig#">...</>

and use --node-id=SecondSignature

**Comment by degzcs** [comment]
@lsh123  many thanks for your help.
I use your solution with a couple more things:
1. define a DTD with the name of the attribute "id" :
```xml
<!DOCTYPE MyDTD [
            <!ATTLIST Signature id ID #IMPLIED>
          ]>
```
2. put the attribute with the name that I put in the first step (e.i id in downcase)
```xml
<Signature id="SecondSignature" xmlns="http://www.w3.org/2000/09/xmldsig#">
```
Note: when I put the id in camelcase the tool did not recognize it.
3. use the param this way:
```sh
$ xmlsec1 ... --node-id 'SecondSignature'  ...
``` 
Note: I don't know why when I put with equal the tool does not recognize the option,

Thanks again :D 
Cheers!
