### ISSUE TITLE
Strange branches in this repository

### ISSUE THREAD

**Issue by cobexer** [lsh123/xmlsec#17]
```# git ls-remote https://github.com/lsh123/xmlsec.git```

> 00718f59834e726178f062e59dbf14bdceaa4a93        HEAD
70b9f385e2a861d0a7e0764f49b73ef317e847dc        refs/heads/aleksey-xmlsec-1.2.21
00718f59834e726178f062e59dbf14bdceaa4a93        refs/heads/master
...
9f62f8f9cc40c5f5dcee1555d3a05b4d82aad391        refs/remotes/origin/1.2.11
554469888b0d828e91a30c997d0c26bc8e730c2f        refs/remotes/origin/XMLSEC_0_0_X_BRANCH
fb4f5a223bcb3fece17e03bb3ea9367a2703ae4f        refs/remotes/origin/XMLSEC_1_2_X_BRANCH
6ac7fb011b93ad7fa92b4ce44b1f908dcdbd4458        refs/remotes/origin/XMLSEC_MSCRYPTO_083103
6f4feedb7cca8336f7c411d3c5a4c2ce6ef485f2        refs/remotes/origin/XMLSEC_NSS_030714
7a1a2063a964a203ab7a1b568d0d839e00e0ca83        refs/remotes/origin/master
5511c222a17fdd06de379317551a01ff2a4340ea        refs/remotes/origin/xmlsec-nss
37eee5633835e20ce1d288dee416de7a26569bb1        refs/remotes/origin/xmlsec-openssl-110
...

The branches with names ```refs/remotes/origin/``` are not supposed to be there.
Also 1.2.11 looks like it wanted to become a tag, but there are no corresponding refs there. Would look like:
> 31d6cc13a52e3e954834e1e04835e76cfb884161        refs/tags/xmlsec-1_2_10
> d76cb664b5dfa55e5d92441b4063a12fdbc479a7        refs/tags/xmlsec-1_2_10^{}

**Comment by lsh123** [comment]
does it create any problems? these branches probably came from several moves between different SVN/GIT hostings

**Comment by cobexer** [comment]
No they don't cause problems - other than costing me 15 minutes trying to figure out where / how I broke my git mirror.
You should probably check if they contain any commit that has not been merged to one of the proper branches! I thought I give you a heads up :)
and the 1.2.11 "branch" wanted to become a tag I guess.

Would be cool if you could clean them up :)
Br,
Christoph

**Comment by lsh123** [comment]
I already fixed 1.2.11 tag. And the rest are references to deleted branches.
