### ISSUE TITLE
xmlSecIORegisterCallbacks will be ignored for custom callbacks

### ISSUE THREAD

**Issue by BastiaanOlij** [lsh123/xmlsec#174]
I'm trying to implement some code that signs attachments that are held in memory but thus exist outside of the XML we're parsing.

After some googling I stumbled upon a discussion with someone who had a similar goal who was directed to the xmlSecIORegisterCallbacks function to register their own URI loader. Eureka! I implemented my own handler, registered it with XMLSec, and then..... nothing...

The problem is because the default implementations are xmlIOHTTP*, xmlIOFTP* and xmlFile*, and specifically that last one. xmlFileMatch will always return true as it does no checking at all resulting in any custom handlers that follow afterwards to be ignored.

The solution would be to either change the position at which custom loaders are added or to find a way to read the xmlInputCallbackTable and copy all callbacks registered with libXML into XMLSec.

**Comment by lsh123** [comment]
Good catch. Fixed in pr #175
