### ISSUE TITLE
__func__ not defined on Microsoft Visual Studio 2012

### ISSUE THREAD

**Issue by cobexer** [lsh123/xmlsec#18]
According to [https://msdn.microsoft.com/en-us/library/b0084kay%28v=vs.120%29.aspx](https://msdn.microsoft.com/en-us/library/b0084kay%28v=vs.120%29.aspx) ```__func__``` is available as of Visual Studio 2013

introduced in [https://github.com/lsh123/xmlsec/commit/a8ad0526fa1a65aee41c8501f83870eb96e97f86#diff-d9904278dc010db60ae8f785beefa956R410](https://github.com/lsh123/xmlsec/commit/a8ad0526fa1a65aee41c8501f83870eb96e97f86#diff-d9904278dc010db60ae8f785beefa956R410)

causes errors like (repeating for every use):
```
	..\src\base64.c(159) : error C2065: '__func__' : undeclared identifier
	..\src\base64.c(159) : warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
	..\src\base64.c(159) : warning C4024: 'xmlSecError' : different types for formal and actual parameter
```

**Comment by lsh123** [comment]
➜  xmlsec git:(master) ✗ git commit -m"use __FUNCTION__ on windows" -a
[master fccb5a0] use __FUNCTION__ on windows
 1 file changed, 1 insertion(+), 1 deletion(-)
