### ISSUE TITLE
Bug in 'xmlSecDSigCtxProcessSignedInfoNode' function

### ISSUE THREAD

**Issue by GuillermoHernan** [lsh123/xmlsec#205]
Function 'xmlSecDSigCtxProcessSignedInfoNode' does not work correctly when the element does not contain a 'SignatureMethod' child element. In this case, it skips the first 'Reference' element, because 'cur' variable is not updated properly.

**Comment by lsh123** [comment]
Technically, SignatureMethod is a required element (https://www.w3.org/TR/xmldsig-core1/#sec-SignatureMethod). However I see the hack that was done to support Microsoft. I'll fix it in a sec.

**Comment by lsh123** [comment]
https://github.com/lsh123/xmlsec/pull/206
