### ISSUE TITLE
Signing fails in  EVP_SignFinal with error 4

### ISSUE THREAD

**Issue by mirow** [lsh123/xmlsec#21]
I'm trying to sign an xml document with my certificates, and for some reason it fails when using xmlsec1 1.2.18 (openssl) + OpenSSL 1.0.1f. **The same certificates + xml files work fine on another machine which has xmlsec1 1.2.9 (openssl)  + OpenSSL 0.9.8e-fips-rhel5.**

The command I'm using is:
`xmlsec1 --sign --output /tmp/signed.xml --pkcs12 mycert.p12 --pwd xxx --trusted-pem vrk.crt /tmp/msg.xml`

The error I receive is:
`func=xmlSecOpenSSLEvpSignatureExecute:file=signatures.c:line=491:obj=rsa-sha256:subj=EVP_SignFinal:error=4:crypto library function failed: 
func=xmlSecTransformDefaultPushBin:file=transforms.c:line=2207:obj=rsa-sha256:subj=xmlSecTransformExecute:error=1:xmlsec library function failed:final=1
func=xmlSecTransformIOBufferClose:file=transforms.c:line=2891:obj=rsa-sha256:subj=xmlSecTransformPushBin:error=1:xmlsec library function failed: 
func=xmlSecTransformC14NPushXml:file=c14n.c:line=279:obj=c14n:subj=xmlOutputBufferClose:error=5:libxml2 library function failed: 
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1236:obj=unknown:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed:transform=c14n
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=614:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxSign:file=xmldsig.c:line=303:obj=unknown:subj=xmlSecDSigCtxSigantureProcessNode:error=1:xmlsec library function failed:`

"crypto library function failed" would suggest the problem is in OpenSSL, right? How can I verify that? Running `openssl pkcs12 -info -in  mycert.p12` works just fine.
I also tried converting the p12 file to pem: `openssl pkcs12 -in mycert.p12 -out mycert.pem -nodes`, which works fine, but trying to sign with the pem file still gives the same error.

**Comment by lsh123** [comment]
I've seen this problem when there was a mismatch between compiled vs runtime version of OpenSSL libraries. Can you double check that you are loading the right version at runtime (e.g. with ldd?)

And yes, this is an error from OpenSSL directly. Bellow XMLSec.

**Comment by mirow** [comment]
Version information (shortened) for OpenSSL:
```
libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fbf09b92000)
libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fbf097b7000)

/usr/bin/openssl:
    libssl.so.1.0.0 (OPENSSL_1.0.1) => /lib/x86_64-linux-gnu/libssl.so.1.0.0
    libssl.so.1.0.0 (OPENSSL_1.0.0) => /lib/x86_64-linux-gnu/libssl.so.1.0.0
    libcrypto.so.1.0.0 (OPENSSL_1.0.1) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
    libcrypto.so.1.0.0 (OPENSSL_1.0.0) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/lib/x86_64-linux-gnu/libssl.so.1.0.0:
    libcrypto.so.1.0.0 (OPENSSL_1.0.1d) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
    libcrypto.so.1.0.0 (OPENSSL_1.0.1) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
    libcrypto.so.1.0.0 (OPENSSL_1.0.0) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```
And for xmlsec1:
```
libxmlsec1-openssl.so.1 => /usr/lib/libxmlsec1-openssl.so.1 (0x00007f924e4f1000)
libxmlsec1.so.1 => /usr/lib/libxmlsec1.so.1 (0x00007f924e293000)
libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f924d1ae000)

/usr/lib/libxmlsec1-openssl.so.1:
    libcrypto.so.1.0.0 (OPENSSL_1.0.0) => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
```

**Comment by lsh123** [comment]
You have multiple versions of openssl installed. Again, you need to make sure that the version you've compiled against is the same as the one you are using at runtime.
