### ISSUE TITLE
gost2012 configure script is broken

### ISSUE THREAD

**Issue by NMorozxov** [lsh123/xmlsec#212]
--enable-gost2012 option is not working. Apply patch above and rebuild with autoreconf.

diff -u -N -r xmlsec1-1.2.26.orig/configure.ac xmlsec1-1.2.26/configure.ac
--- xmlsec1-1.2.26.orig/configure.ac	2018-07-30 11:39:25.108304145 +0300
+++ xmlsec1-1.2.26/configure.ac	2018-07-30 11:39:49.472066430 +0300
@@ -2008,7 +2008,7 @@
 dnl See do we need GOST2012 support
 dnl ==========================================================================
 AC_MSG_CHECKING(for EXPERMIENTAL GOST2012 support)
-AC_ARG_ENABLE(gost,   [  --enable-gost2012       enable EXPERMIENTAL GOST2012 support (no)])
+AC_ARG_ENABLE(gost2012,   [  --enable-gost2012       enable EXPERMIENTAL GOST2012 support (no)])
 if test "z$enable_gost2012" != "zyes" ; then
     XMLSEC_DEFINES="$XMLSEC_DEFINES -DXMLSEC_NO_GOST2012=1"
     XMLSEC_NO_GOST2012="1"

**Comment by lsh123** [comment]
Thanks!
