### ISSUE TITLE
SystemError: null argument to internal routine with libressl

### ISSUE THREAD

**Issue by GaretJax** [lsh123/xmlsec#216]
`xmlsec` currently fails to import when using compiled against libressl:

```
# python -c 'import xmlsec'
func=xmlSecCryptoDLLibraryCreate:file=dl.c:line=130:obj=unknown:subj=lt_dlopenext:error=7:io function failed:name="libxmlsec1-openssl"; errno=2
func=xmlSecCryptoDLGetLibraryFunctions:file=dl.c:line=436:obj=unknown:subj=xmlSecCryptoDLLibraryCreate:error=1:xmlsec library function failed:crypto=openssl
func=xmlSecCryptoDLLoadLibrary:file=dl.c:line=393:obj=unknown:subj=xmlSecCryptoDLGetLibraryFunctions:error=1:xmlsec library function failed:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: null argument to internal routine
```

Steps to reproduce:
```
docker run -it --rm divio/base:1.1-py3.6-alpine3.8-dev sh
apk add xmlsec-dev
pip install xmlsec
python -c 'import xmlsec'
```

Version information:
```
xmlsec 1.2.25-r2
libressl 2.7.4-r0
python 3.6.6
python-xmlsec 1.3.3
```

**Comment by lsh123** [comment]
https://amir.rachum.com/blog/2016/09/17/shared-libraries/#runtime-search-path

**Comment by GaretJax** [comment]
Works with:
```
xmlsec 1.2.25-r1
libressl 2.6.5-r0
python 3.6.6
python-xmlsec 1.3.3
```

**Comment by GaretJax** [comment]
Thanks for the quick answer @lsh123. Sadly I fail to see how that link helps me further.

**Comment by lsh123** [comment]
The error means that shared library "libxmlsec1-openssl" was not found or not loaded (e.g. due to version incompatibility)

func=xmlSecCryptoDLLibraryCreate:file=dl.c:line=130:obj=unknown:subj=lt_dlopenext:error=7:io function failed:name="libxmlsec1-openssl"; errno=2

**Comment by GaretJax** [comment]
libxmlsec1-openssl is provided by the [xmlsec package](https://pkgs.alpinelinux.org/contents?file=&path=&name=xmlsec&branch=v3.8&repo=community&arch=x86_64) and available on the system:

```
# ls -1 /usr/lib/libxmlsec1-openssl.*
/usr/lib/libxmlsec1-openssl.la
/usr/lib/libxmlsec1-openssl.so
/usr/lib/libxmlsec1-openssl.so.1
/usr/lib/libxmlsec1-openssl.so.1.2.25
```

This is the same version as on [alpine 3.7](https://pkgs.alpinelinux.org/contents?file=&path=&name=xmlsec&branch=v3.7&repo=community&arch=x86_64) (which ships with a different libressl version 2.6.5 instead of 2.7.4).

**Comment by GaretJax** [comment]
I don't know it if means anything, but libxmlsec1-openssl is not listed in the ldd output (just `libxmlsec1`, which is indeed found):

```
# ldd xmlsec.cpython-36m-x86_64-linux-gnu.so
        ldd (0x7f785bc69000)
        libxmlsec1.so.1 => /usr/lib/libxmlsec1.so.1 (0x7f785b7ec000)
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0x7f785b4c3000)
        libpython3.6m.so.1.0 => /usr/local/lib/libpython3.6m.so.1.0 (0x7f785af8a000)
        libc.musl-x86_64.so.1 => ldd (0x7f785bc69000)
        libxslt.so.1 => /usr/lib/libxslt.so.1 (0x7f785ad52000)
        libltdl.so.7 => /usr/lib/libltdl.so.7 (0x7f785ab49000)
        libz.so.1 => /lib/libz.so.1 (0x7f785a932000)
```
