### ISSUE TITLE
I have a following xml sample and private key, but failed to decrypt.

### ISSUE THREAD

**Issue by SijieDingEsna** [lsh123/xmlsec#217]
[tmpctNJ69.txt](https://github.com/lsh123/xmlsec/files/2319253/tmpctNJ69.txt)

[esnacom.txt](https://github.com/lsh123/xmlsec/files/2319256/esnacom.txt)

The tmpctNJ69.txt is the decrypted xml and esnacom.txt is the private key.
When I run the following command

xmlsec1 --decrypt --privkey-pem /Users/ericd/Downloads/esnacom.txt --id-attr:ID EncryptedKey --output test.xml /Users/ericd/Downloads/tmpctNJ69.txt

I got the following error:
func=xmlSecXPathDataExecute:file=xpath.c:line=247:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('_2f31a3975401fd4f61e8219dd0597745')); xml error: 0: NULL
func=xmlSecXPathDataListExecute:file=xpath.c:line=330:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformXPathExecute:file=xpath.c:line=431:obj=xpointer:subj=xmlSecXPathDataListExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2109:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1045:obj=xpointer:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxExecute:file=transforms.c:line=1092:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecKeyDataRetrievalMethodXmlRead:file=keyinfo.c:line=1088:obj=retrieval-method:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed: 
func=xmlSecKeyInfoNodeRead:file=keyinfo.c:line=124:obj=retrieval-method:subj=xmlSecKeyDataXmlRead:error=1:xmlsec library function failed:node=RetrievalMethod
func=xmlSecKeysMngrGetKey:file=keys.c:line=1237:obj=unknown:subj=xmlSecKeyInfoNodeRead:error=1:xmlsec library function failed:node=KeyInfo
func=xmlSecEncCtxEncDataNodeRead:file=xmlenc.c:line=783:obj=unknown:subj=unknown:error=45:key is not found:encMethod=aes256-cbc
func=xmlSecEncCtxDecryptToBuffer:file=xmlenc.c:line=598:obj=unknown:subj=xmlSecEncCtxEncDataNodeRead:error=1:xmlsec library function failed: 
func=xmlSecEncCtxDecrypt:file=xmlenc.c:line=526:obj=unknown:subj=xmlSecEncCtxDecryptToBuffer:error=1:xmlsec library function failed: 
Error: failed to decrypt file
Error: failed to decrypt file "/Users/ericd/Downloads/tmpctNJ69.txt"

I try it under ubuntu and Mac OS, both of them get same error.

**Comment by lsh123** [comment]
section 3.2 from FAQ
