### ISSUE TITLE
XMLSEC for Windows

### ISSUE THREAD

**Issue by daniel-sherwood** [lsh123/xmlsec#227]
I notice that the Windows binaries linked from the homepage at https://www.zlatkovic.com/pub/libxml/ and https://www.zlatkovic.com/pub/libxml/64bit/ are versions 1.2.18 & 1.2.20 respectively. 

Is there an alternative source for up to date Windows binaries, or a guideline for compiling them from source?

**Comment by lsh123** [comment]
There are README files in win32/ folders for both libxml2 and xmlsec that have all the necessary instructions.
