### ISSUE TITLE
Incompatibility with Java ECDSA signatures

### ISSUE THREAD

**Issue by ralisi** [lsh123/xmlsec#228]
I have encountered an incompatbility with the Java signature implementation. The problem happens rarely and fails at the check of the signature length at https://github.com/lsh123/xmlsec/blob/master/src/openssl/signatures.c#L1002
 
The SignatureValue field contains the base64 coded concatenation of the primes _r_ and _s_. The code in question assumes that the length of these two integers is always the same, which I think is correct according to RFC 6931.
 
The Java implementation however will discard leading zeros, if both numbers have leading zeros. See https://github.com/unofficial-openjdk/openjdk/blob/531ef5d0ede6d733b00c9bc1b6b3c14a0b2b3e81/src/java.xml.crypto/share/classes/com/sun/org/apache/xml/internal/security/algorithms/implementations/ECDSAUtils.java#L75
The resulting _SignatureValue_ will be always even, but not necessary the expected amount.
 
As I think the current implementation is technically correct, I will also file a respective bug report on the java side on the ubuntu bugtracker: https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1797101
 
On the other hand, as the Java implementation is out in the wild, I would propose to also accept such a signature.

 ```
         xmlSecInternalError("xmlSecOpenSSLSignatureEcdsaSignatureHalfSize", NULL);
         goto done;
     }
     /* check size */
     if(signSize != 2 * signHalfSize) {
-        xmlSecInvalidSizeError("ECDSA signature", signSize, 2 * signHalfSize,
-                               NULL);
-        goto done;
+        /* be generous when leading zeros were cut off. e.g. for Java */
+        if(signSize < 2 * signHalfSize && signSize%2 == 0) {
+            signHalfSize = signSize / 2;
+        } else {
+            xmlSecInvalidSizeError("ECDSA signature", signSize, 2 * signHalfSize,
+                                   NULL);
+            goto done;
+        }
     }
     /* create/read signature */
     sig = ECDSA_SIG_new();
     if (sig == NULL) {
         xmlSecOpenSSLError("DSA_SIG_new", NULL);
```

**Comment by lsh123** [comment]
Can you send a PR with a test case? I am not sure this is enough to fix the problem. What if r and s have different number of 0s?

**Comment by ralisi** [comment]
If they have different amounts of zeros cut off, then we are out of luck as there is no way to tell where one ends an the other one stops. The way I have understood the java implementation, they at least take care that both numbers are always of the same size. So the input can just be split in two halves.
The problem in telling for sure is that it depends upon the actual values of r and s, which are subject to randomness.

**Comment by lsh123** [comment]
OK, do you have a test case?

**Comment by ralisi** [comment]
Yes, see [testcase.zip](https://github.com/lsh123/xmlsec/files/2473613/testcase.zip).
It contains an xml file with a too short SignatureValue, as occasionally produced by Java.

Currently, the output is:

```
/usr/bin/xmlsec1 verify --trusted testcase.crt testcase.xml
func=xmlSecOpenSSLSignatureEcdsaVerify:file=signatures.c:line=1057:obj=unknown:subj=unknown:error=11:invalid size:invalid size for 'ECDSA signature': actual=130 is not equal to expected=132
func=xmlSecOpenSSLSignatureVerify:file=signatures.c:line=455:obj=ecdsa-sha512:subj=verifyCallback:error=1:xmlsec library function failed: 
func=xmlSecTransformVerifyNodeContent:file=transforms.c:line=1527:obj=ecdsa-sha512:subj=xmlSecTransformVerify:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=356:obj=unknown:subj=xmlSecTransformVerifyNodeContent:error=1:xmlsec library function failed: 
Error: signature failed 
ERROR
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
Error: failed to verify file "testcase.xml"
```

or now with the change of accepting shorter lengths and splitting the byte array simply in half:

```
/usr/bin/xmlsec1 verify --trusted testcase.crt testcase.xml
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0
```

**Comment by lsh123** [comment]
Interesting. NSS works out of the box bug MSCNG (BCryptVerifySignature) fails.

**Comment by lsh123** [comment]
Fixed both mscng and gnutls.
