### ISSUE TITLE
boringssl support request

### ISSUE THREAD

**Issue by chenbd** [lsh123/xmlsec#230]
Hello Developers:
We want to use xmlsec library under android, but recent android version removed openssl and use boringssl instead. 
about boring ssl: https://github.com/google/boringssl

**Comment by lsh123** [comment]
XMLSec is open source and I love patches.

**Comment by petrovr** [comment]
lsh123 wrote:
> XMLSec is open source and I love patches.

BoringSSL does not provide yet stable API.
I cannot see why someone would like to spend time on this.
OpenSSL could be compiled and distributed as application specific library.

Regards,
Roumen Petrov

**Comment by chenbd** [comment]
Hello @lsh123 
I'm not sure about deal with `DSA_get0_engine` in `src/openssl/evp.c` for boring ssl,  struct dsa_st does not have member `engine`, would you please give some advice?

**Comment by lsh123** [comment]
DSA_get0_engine is used to figure out if a given key is private or public.

Not sure what do you mean by RSA_padding_add_PKCS1_OAEP/RSA_padding_check_PKCS1_OAEP. Does boring ssl support RSA OAEP?

**Comment by chenbd** [comment]
@lsh123 
I just made a commit for boringssl, it is at https://github.com/mxnavi/xmlsec/commit/c4c403ac1329f52ef46749ec2376655c6b3db9cf.

Would you please help give some advice?
I'm not familiar with SSL and just made it compiled and not tested under real device .

And boringssl is at [http://androidxref.com/7.1.1_r6/xref/external/boringssl/](url)

**Comment by chenbd** [comment]
@lsh123 New pull request #237

**Comment by lsh123** [comment]
I've made some changes to #237 and submitted #240 which adds boringssl support against master (https://github.com/google/boringssl). However, the boringssl support is really hacky already and given boringssl lack of commitment to a stable APIs, I expect it to break frequent and often.
