### ISSUE TITLE
xmlsec broken for (at least) mscrypto and mscng backends on 64-bit Windows

### ISSUE THREAD

**Issue by snargit** [lsh123/xmlsec#238]
32-bit works fine but 64-bit seems to have internal memory overwrite problems. I've seen this with the XML encrypt examples. Not tested signing. I wonder if it's related to the fixes for compiler warnings from MSVC?

**Comment by snargit** [comment]
Ah no - it seems that win32\makefile.msvc has XMLSEC_NO_SIZE_T defined which makes xmlSecSize an unsigned 32-bit type regardless. It needs to be 64-bit on a 64-bit build.

**Comment by lsh123** [comment]
XMLSec has Windows 64 CI builds passing so I would assume that this is not about the tests in xmlsec but in the application you've built. In this case, you do need to define XMLSEC_NO_SIZE_T in your code.
