### ISSUE TITLE
xmlsec1 --list-transforms returns IO Error

### ISSUE THREAD

**Issue by jbmfg** [lsh123/xmlsec#260]
On some systems the below command returns "error : Unknown IO error" before listing the Registered transform klasses.  Not sure what the cause is as the list of klasses returned looks correct.  What might cause this "error Unknown IO error" to appear on only some machines?  Where is xmlsec1 pulling these transform klasses from?

Issue:
[root@CentOS ~] xmlsec1 --list-transforms 
error : Unknown IO error 
Registered transform klasses: 
"base64","enveloped-signature","c14n","c14n-with-comments","c14n11","c14n11-with-comments","exc-c14n","exc-c14n-with-comments","xpath","xpath2","xpointer","xslt","aes128-cbc","aes192-cbc","aes256-cbc","kw-aes128","kw-aes192","kw-aes256","tripledes-cbc","kw-tripledes","dsa-sha1","dsa-sha256","ecdsa-sha1","ecdsa-sha224","ecdsa-sha256","ecdsa-sha384","ecdsa-sha512","hmac-md5","hmac-ripemd160","hmac-sha1","hmac-sha224","hmac-sha256","hmac-sha384","hmac-sha512","md5","ripemd160","rsa-md5","rsa-ripemd160","rsa-sha1","rsa-sha224","rsa-sha256","rsa-sha384","rsa-sha512","rsa-1_5","rsa-oaep-mgf1p","sha1","sha224","sha256","sha384","sha512" 

Expected:
[root@CentOS ~] xmlsec1 --list-transforms 
Registered transform klasses: 
"base64","enveloped-signature","c14n","c14n-with-comments","c14n11","c14n11-with-comments","exc-c14n","exc-c14n-with-comments","xpath","xpath2","xpointer","xslt","aes128-cbc","aes192-cbc","aes256-cbc","kw-aes128","kw-aes192","kw-aes256","tripledes-cbc","kw-tripledes","dsa-sha1","dsa-sha256","ecdsa-sha1","ecdsa-sha224","ecdsa-sha256","ecdsa-sha384","ecdsa-sha512","hmac-md5","hmac-ripemd160","hmac-sha1","hmac-sha224","hmac-sha256","hmac-sha384","hmac-sha512","md5","ripemd160","rsa-md5","rsa-ripemd160","rsa-sha1","rsa-sha224","rsa-sha256","rsa-sha384","rsa-sha512","rsa-1_5","rsa-oaep-mgf1p","sha1","sha224","sha256","sha384","sha512"

**Comment by lsh123** [comment]
This doesn't look like an xmlsec error:

xmlsec$ grep -r 'error :' *
src/mscrypto/x509vfy.c:        * trial and error :( WK
src/mscrypto/x509.c:     * trial and error :( WK

Might be one of the shared libraries (openssl?) complaining about loading config files or something.

**Comment by lsh123** [comment]
Actually, looks like it can be coming from LibXML2: 

https://www.aleksey.com/pipermail/xmlsec/2006/007804.html

**Comment by jbmfg** [comment]
Right, but i was hoping to find out what xmlsec1 is loading when doing --list-transforms.  This error appears to happen when libxml2 loads an xml but in this case i dont know what is being loaded by libxml2.  Can you help with that?

**Comment by lsh123** [comment]
Nothing is loaded explicitly. However libxml2 initialization might be loading DTDs and other things.

**Comment by jbmfg** [comment]
Ok, thanks for that.  So when you run xmlsec1 --list-transforms, where are those transforms pulled from?

**Comment by lsh123** [comment]
Whatever is configured during xmlsec build. There are no config files for xmlsec itself.
