### ISSUE TITLE
Xcoden10.2 Error  file not found

### ISSUE THREAD

**Issue by cmiosdeveloper** [lsh123/xmlsec#264]
Error: 'xmlsec/xmlsec.h' file not found.

I have installed XML Security Library and written Header search path for this library but still I am getting error. Can you help me, how to import this library on Xcode IOS. Do you have Pod file for the same. because openssl they provide pod file installation that solved my issue. But for xmlsec didn't found any pod file. can you suggest me ?

**Comment by lsh123** [comment]
Not an xmlsec bug
