### ISSUE TITLE
[ossfuzz] Build integration

### ISSUE THREAD

**Issue by bshastry** [lsh123/xmlsec#265]
Hello,

I would like to extend xmlsec's autoconf build configuration so that oss-fuzz harness can be built and used for CI/regression testing.

How shall I get started?

Thank you.

**Comment by lsh123** [comment]
I believe you already enabled oss-fuzz integration. Not sure what else do you plan to do here.

**Comment by bshastry** [comment]
I'd like to do the following things
  - add a makefile target to build ossfuzz binaries
  - add a CI that does regression testing of fuzzer targets

I'll send a PR soon
