### ISSUE TITLE
xmlSecX509DataGetNodeContent has no deleteChildren argument anymore, breaks pyxmlsec

### ISSUE THREAD

**Issue by erny** [lsh123/xmlsec#266]
In: 2632a64a6dc414c9b253471fad00d4a117461eaf  (2016-10-14) deleteChildren is removed 

This breaks pyxmlsec python binding. This seems between version 1.24 and 1.25. How could be handle this in C source code? (#if ...)

https://github.com/dnet/pyxmlsec/issues/6

**Comment by lsh123** [comment]
It was done in 2016:

https://github.com/lsh123/xmlsec/commit/2632a64a6dc414c9b253471fad00d4a117461eaf#diff-ae9050c2ab376b07798ce5992083ce06

Probably it's time to update bindings?
