### ISSUE TITLE
libxml2 library function failed:expr=xpointer

### ISSUE THREAD

**Issue by shubenkovva** [lsh123/xmlsec#268]
The command is:

**xmlsec1 --verify --trusted-pem /Users/user/projects/lua_saml/src/root.pem  --trusted-pem /Users/user/projects/lua_saml/src/idp.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:Response ./temp.xml**

The output:

xmlsec1 --verify --trusted-pem /Users/user/projects/lua_saml/src/root.pem  --trusted-pem /Users/user/projects/lua_saml/src/idp.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:protocol:Response ./temp.xml
**func=xmlSecXPathDataExecute:file=xpath.c:line=247:obj=unknown:subj=xmlXPtrEval:error=5:libxml2 library function failed:expr=xpointer(id('s2784d554ed7c3ee820001478b9aa9b3fad21eab81')); xml error: 0: NULL
func=xmlSecXPathDataListExecute:file=xpath.c:line=330:obj=unknown:subj=xmlSecXPathDataExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformXPathExecute:file=xpath.c:line=431:obj=xpointer:subj=xmlSecXPathDataListExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformDefaultPushXml:file=transforms.c:line=2109:obj=xpointer:subj=xmlSecTransformExecute:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxXmlExecute:file=transforms.c:line=1045:obj=xpointer:subj=xmlSecTransformPushXml:error=1:xmlsec library function failed: 
func=xmlSecTransformCtxExecute:file=transforms.c:line=1092:obj=unknown:subj=xmlSecTransformCtxXmlExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1408:obj=unknown:subj=xmlSecTransformCtxExecute:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessReferences:file=xmldsig.c:line=753:obj=Reference:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=517:obj=unknown:subj=xmlSecDSigCtxProcessReferences:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=346:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature failed 
ERROR
SignedInfo References (ok/all): 0/1
Manifests References (ok/all): 0/0**

The xml file is:

<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="s2dfb6cf5fb355778f428ba1c8734f6528a027aa94" InResponseTo="_e59f536c8797c48704aa89649f38fd44" Version="2.0" IssueInstant="2019-06-16T12:27:32Z" Destination="http://sp.example.com:4443/sso/finish-login"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://idp.ssocircle.com</saml:Issuer><samlp:Status xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
<samlp:StatusCode xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Value="urn:oasis:names:tc:SAML:2.0:status:Success">
</samlp:StatusCode>
</samlp:Status><saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="s2784d554ed7c3ee820001478b9aa9b3fad21eab81" IssueInstant="2019-06-16T12:27:32Z" Version="2.0">
<saml:Issuer>https://idp.ssocircle.com</saml:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:SignedInfo>
<ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<ds:Reference URI="#s2784d554ed7c3ee820001478b9aa9b3fad21eab81">
<ds:Transforms>
<ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</ds:Transforms>
<ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<ds:DigestValue>gbdIFH/RrK5oyomWWEemIB1Uf+Y=</ds:DigestValue>
</ds:Reference>
</ds:SignedInfo>
<ds:SignatureValue>
U9hthpTrgOd5M/+nCxjyY4Ju9BCbLf1YI8RWeVkYGtKbHRWRS7J2NqT5/xEkWaeqnUwfKiDYe/Vg
Ohk2f26kro4lm0HRoCXm4T2scg+5qLqtd3YYpRjOiLbX3bQbcM2M1wjqOReqqNSZ43wbFel+tDTT
7HcUJk3/QlpzMbQyCJeSzD9xtJa5RVzy+MV6URLXtpo0796fXz5zPWVoX4JJWPO+jTRKs2tHKxTr
S1VWHJ1WpmEBf0g0YiDIABo9lJtC+mVEQt8w5ouyvbh0fzogpc3FZmu79g5gmmeu6wHKME8ai3bx
RCVVpkuiLbRp3aMEJzHjWruuKESLk1WHrqmj9w==
</ds:SignatureValue>
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIEYzCCAkugAwIBAgIDIAZmMA0GCSqGSIb3DQEBCwUAMC4xCzAJBgNVBAYTAkRFMRIwEAYDVQQK
DAlTU09DaXJjbGUxCzAJBgNVBAMMAkNBMB4XDTE2MDgwMzE1MDMyM1oXDTI2MDMwNDE1MDMyM1ow
PTELMAkGA1UEBhMCREUxEjAQBgNVBAoTCVNTT0NpcmNsZTEaMBgGA1UEAxMRaWRwLnNzb2NpcmNs
ZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCAwWJyOYhYmWZF2TJvm1VyZccs
3ZJ0TsNcoazr2pTWcY8WTRbIV9d06zYjngvWibyiylewGXcYONB106ZNUdNgrmFd5194Wsyx6bPv
njZEERny9LOfuwQaqDYeKhI6c+veXApnOfsY26u9Lqb9sga9JnCkUGRaoVrAVM3yfghv/Cg/QEg+
I6SVES75tKdcLDTt/FwmAYDEBV8l52bcMDNF+JWtAuetI9/dWCBe9VTCasAr2Fxw1ZYTAiqGI9sW
4kWS2ApedbqsgH3qqMlPA7tg9iKy8Yw/deEn0qQIx8GlVnQFpDgzG9k+jwBoebAYfGvMcO/BDXD2
pbWTN+DvbURlAgMBAAGjezB5MAkGA1UdEwQCMAAwLAYJYIZIAYb4QgENBB8WHU9wZW5TU0wgR2Vu
ZXJhdGVkIENlcnRpZmljYXRlMB0GA1UdDgQWBBQhAmCewE7aonAvyJfjImCRZDtccTAfBgNVHSME
GDAWgBTA1nEA+0za6ppLItkOX5yEp8cQaTANBgkqhkiG9w0BAQsFAAOCAgEAAhC5/WsF9ztJHgo+
x9KV9bqVS0MmsgpG26yOAqFYwOSPmUuYmJmHgmKGjKrj1fdCINtzcBHFFBC1maGJ33lMk2bM2THx
22/O93f4RFnFab7t23jRFcF0amQUOsDvltfJw7XCal8JdgPUg6TNC4Fy9XYv0OAHc3oDp3vl1Yj8
/1qBg6Rc39kehmD5v8SKYmpE7yFKxDF1ol9DKDG/LvClSvnuVP0b4BWdBAA9aJSFtdNGgEvpEUqG
kJ1osLVqCMvSYsUtHmapaX3hiM9RbX38jsSgsl44Rar5Ioc7KXOOZFGfEKyyUqucYpjWCOXJELAV
Azp7XTvA2q55u31hO0w8Yx4uEQKlmxDuZmxpMz4EWARyjHSAuDKEW1RJvUr6+5uA9qeOKxLiKN1j
o6eWAcl6Wr9MreXR9kFpS6kHllfdVSrJES4ST0uh1Jp4EYgmiyMmFCbUpKXifpsNWCLDenE3hllF
0+q3wIdu+4P82RIM71n7qVgnDnK29wnLhHDat9rkC62CIbonpkVYmnReX0jze+7twRanJOMCJ+lF
g16BDvBcG8u0n/wIDkHHitBI7bU1k6c6DydLQ+69h8SCo6sO9YuD+/3xAGKad4ImZ6vTwlB4zDCp
u6YgQWocWRXE+VkOb+RBfvP755PUaLfL63AFVlpOnEpIio5++UjNJRuPuAA=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</ds:Signature><saml:Subject>
<saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" NameQualifier="https://idp.ssocircle.com" SPNameQualifier="http://sp.example.com:4443/sso">shubenkov</saml:NameID><saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
<saml:SubjectConfirmationData InResponseTo="_e59f536c8797c48704aa89649f38fd44" NotOnOrAfter="2019-06-16T12:37:32Z" Recipient="http://sp.example.com:4443/sso/finish-login"/></saml:SubjectConfirmation>
</saml:Subject><saml:Conditions NotBefore="2019-06-16T12:17:32Z" NotOnOrAfter="2019-06-16T12:37:32Z">
<saml:AudienceRestriction>
<saml:Audience>http://sp.example.com:4443/sso</saml:Audience>
</saml:AudienceRestriction>
</saml:Conditions>
<saml:AuthnStatement AuthnInstant="2019-06-16T06:35:03Z" SessionIndex="s2b6e0217787534cf49fef15f485327a5b7a6c9801"><saml:AuthnContext><saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement><saml:AttributeStatement><saml:Attribute Name="UserID"><saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">shubenkov</saml:AttributeValue></saml:Attribute></saml:AttributeStatement></saml:Assertion></samlp:Response>

Cert file: https://www.ssocircle.com/en/idp-tips-tricks/public-idp-configuration/
**I have successfully checked SAML Response here https://www.samltool.com/validate_response.php. It is good.**

**Comment by lsh123** [comment]
Could you please attach the XML file instead of copy/pasting it? And also attach both certificates from the command line? Currently with one certificate from the link above I got "certificate verification failed" error.

Thanks!

**Comment by shubenkovva** [comment]
Hello.

All data in attached archive. For reliability the the xml file was encoded to base64 format. I use OSX operating system.
[xml_example_and_cert.zip](https://github.com/lsh123/xmlsec/files/3305647/xml_example_and_cert.zip)
Thanks

**Comment by lsh123** [comment]
The issue is that ID attribute was not found (I assume you already found the FAQ since you are using the --id-attr flag). And it seems that libxml2 error for this situation changed in the newer version thus it's hard to understand it. 

Anyway, using the correct namespace/nodename for this ID attribute I can successfully verify the file:

$ xmlsec1 --verify --trusted-pem root.pem --trusted-pem idp.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:assertion:Assertion ./temp.xml
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0

**Comment by AASH1234** [comment]
Is there any function to specify id-attr in code??

**Comment by lsh123** [comment]
https://github.com/lsh123/xmlsec/blob/5dc2b1171b70aa4bf8cd5f35d41761dc6e054f3f/apps/xmlsec.c#L2566

**Comment by bjm88** [comment]
trying to also use pysaml2 that calls this, /usr/local/bin/xmlsec1 --verify --enabled-reference-uris empty,same-doc --enabled-key-data raw-x509-cert --pubkey-cert-pem ./app/python_api/resolvers/mychart_sp_poc_combo_cert.pem --id-attr:ID urn:oasis:names:tc:SAML:2.0:metadata:EntitiesDescriptor --output /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmpehi5pxzy.xml /var/folders/zj/0j90r53n281d0fzghl872w5r0000gn/T/tmpm5nafyjw.xml
