### ISSUE TITLE
Add support for conan package manager

### ISSUE THREAD

**Issue by dmn-star-home** [lsh123/xmlsec#270]
https://conan.io
Conan, the C / C++ Package Manager for Developers

The open source, decentralized and multi-platform
package manager to create and share all your native binaries.

Please add support for conan package manager. I already added xmlsec to conan wishlist
https://github.com/conan-io/wishlist/issues/233

May be someone can write or help to write the conan recipe for xmlsec.

**Comment by lsh123** [comment]
There is a tracking bug on Conan already.
