### ISSUE TITLE
Configure: --enable-shared=no / --with-libxml-src / --with-libxslt-src

### ISSUE THREAD

**Issue by stefan-kaltenberger** [lsh123/xmlsec#271]
The `configure` script doesn't recognize my `libxml` / `libxslt` build specified with `--with-libxml-src` / `--with-libxslt-src` if I build all of them using `--enable-shared=no` as it uses `.libs/libxml2.so` / `libxslt/.libs/libxslt.so` as `LIBXML_LIB_MARKER` / `LIBXSLT_LIB_MARKER`. Could you change that to use the archive `libxml2.a` / `libxslt.a` (which should exist in any case) instead?
```
diff -Naur xmlsec1-1.2.28/configure xmlsec1-patch/configure
--- xmlsec1-1.2.28/configure    2019-04-16 18:39:59.000000000 +0200
+++ xmlsec1-patch/configure     2019-07-11 11:35:41.401467679 +0200
@@ -13938,7 +13938,7 @@
 LIBXML_INCLUDE_DIR="$COMMON_INCLUDE_DIR /usr/include/libxml2 /usr/local/include/libxml2 /usr/local/libxml2/include"
 LIBXML_LIB_DIR="$COMMON_LIB_DIR /usr/local/libxml2/lib"
 LIBXML_INCLUDE_MARKER="libxml/xmlversion.h"
-LIBXML_LIB_MARKER="libxml2$shrext"
+LIBXML_LIB_MARKER="libxml2.$libext"
 LIBXML_LIBS_LIST="-lxml2"
 LIBXML_CONFIG="xml2-config"

@@ -14266,7 +14266,7 @@
 LIBXSLT_LIB_DIR="$COMMON_LIB_DIR /usr/local/libxslt/lib"
 LIBXSLT_CONFIG="xslt-config"
 LIBXSLT_INCLUDE_MARKER="libxslt/xsltconfig.h"
-LIBXSLT_LIB_MARKER="libxslt$shrext"
+LIBXSLT_LIB_MARKER="libxslt.$libext"
 LIBXSLT_LIBS_LIST="-lxslt"
```

**Comment by petrovr** [comment]
stefan-kaltenberger wrote:
> The `configure` script doesn't recognize my `libxml` / `libxslt` build specified with `--with-libxml-src` / `--with-libxslt-src` if I build all of them using `--enable-shared=no` as it uses `.libs/libxml2.so` / `libxslt/.libs/libxslt.so` as `LIBXML_LIB_MARKER` / `LIBXSLT_LIB_MARKER`. Could you change that to use the archive `libxml2.a` / `libxslt.a` (which should exist in any case) instead?

My build is also based on use of  libxml and libxslt from build tree. 
I'm not sure why use chose "static build", as shared is fine with me.
Remark: I know that some in installations static linked in preffered.


> ```
> diff -Naur xmlsec1-1.2.28/configure xmlsec1-patch/configure
> --- xmlsec1-1.2.28/configure    2019-04-16 18:39:59.000000000 +0200
> +++ xmlsec1-patch/configure     2019-07-11 11:35:41.401467679 +0200
> @@ -13938,7 +13938,7 @@
>   LIBXML_INCLUDE_DIR="$COMMON_INCLUDE_DIR /usr/include/libxml2 /usr/local/include/libxml2 /usr/local/libxml2/include"
>   LIBXML_LIB_DIR="$COMMON_LIB_DIR /usr/local/libxml2/lib"
>   LIBXML_INCLUDE_MARKER="libxml/xmlversion.h"
> -LIBXML_LIB_MARKER="libxml2$shrext"
> +LIBXML_LIB_MARKER="libxml2.$libext"
>   LIBXML_LIBS_LIST="-lxml2"
>   LIBXML_CONFIG="xml2-config"
Above is not acceptable just by one reason - it works fine with shared 
build. If changed it will break link with shared libraries.

I have no idea why author decide to perform extra checks for existence 
of library.
Check is not correct as nobody know how linkers work. Suffix could be 
one of .so, or .a, or .dylib, or .dll.a, or .lib (static or shared ;) ! 
). Linker could search for specific prefix.
Also is not clear how linked search directories - all "name" 
combinations in a directory before to move to next or a combination in 
all directories before to move to next.

Not on last please is architecture. What if you found libfoo.so. You 
build is for x86 but found libfoo.so is for arm8 ;).


Aleksey,
I will trust on user configuration, i.e. I recommend removal of those 
checks for library existence.


Regard,
Roumen

**Comment by lsh123** [comment]
Trust no-one :) I have a better fix: 

https://github.com/lsh123/xmlsec/commit/c4d0493d545b99194eea1b2b058930d5a9bb91b1
