### ISSUE TITLE
Is it possible to input the xml template as a string instead of pointing to a filename?

### ISSUE THREAD

**Issue by drupalista-br** [lsh123/xmlsec#273]
Normally I would do something like:

`$ xmlsec1 --sign --privkey-pem MY_CERT_FILE.pem MY_TEMPLATE_FILE.xml`

The above would spit out the signed xml string on the terminal screen.

I would like to do something like this though:

`$ xmlsec1 --sign --privkey-pem MY_CERT_FILE.pem '<?xml version="1.0" encoding="UTF-8"?><Envelope><Data>Hello, World!</Data></Envelope>'`

Obviously the above command does NOT work.

I am hoping for some sort of option flag before the xml input string which would allow me to accomplish just that.

**Comment by drupalista-br** [comment]
There are two dirty solutions for this, 

`$ xmlsec1 --sign --privkey-pem cert.pem <(echo 'XML TEMPLATE STRING HERE')`

 or

 `$ xmlsec1 --sign --privkey-pem cert.pem /dev/stdin <<<'XML TEMPLATE STRING HERE'`

See details at https://superuser.com/questions/939746/pass-text-to-program-expecting-a-file

**Comment by lsh123** [comment]
This is not possible at the moment but I accept patches.

**Comment by lsh123** [comment]
Actually, this works already:

xmlsec1 --sign  /dev/stdin <<<'XML TEMPLATE STRING HERE'
