### ISSUE TITLE
xmlsec tool failed to execute <Manifest> node

### ISSUE THREAD

**Issue by DebasishNath1989** [lsh123/xmlsec#279]
I have a node in my xml like below:
<Object Id="sample">
<Manifest>
<Prerequisites></Prerequisites>
</Manifest>
</Object>

While signing my xml with xmlsec tool (version 1.2.18), I am getting the below error:
func=xmlSecDSigCtxProcessManifestNode:file=..\src\xmldsig.c:line=1048:obj=unknown:subj=Prerequisites:error=27:unexpected node:
func=xmlSecDSigCtxProcessObjectNode:file=..\src\xmldsig.c:line=950:obj=unknown:subj=xmlSecDSigCtxProcessManifestNode:error=1:xmlsec library function failed:
func=xmlSecDSigCtxProcessSignatureNode:file=..\src\xmldsig.c:line=523:obj=unknown:subj=xmlSecDSigCtxProcessObjectNode:error=1:xmlsec library function failed:
func=xmlSecDSigCtxSign:file=..\src\xmldsig.c:line=303:obj=unknown:subj=xmlSecDSigCtxSigantureProcessNode:error=1:xmlsec library function failed:
Error: signature failed

Is it wrong way to use "Manifest" node like my way <Manifest>?
If i modify the string "Manifest", it's working fine.

Thanks

**Comment by lsh123** [comment]
https://www.w3.org/TR/xmldsig-core1/#sec-Manifest
