### ISSUE TITLE
Allow XML_PARSE_HUGE parameter when calling xmlSecEncCtxDecrypt().

### ISSUE THREAD

**Issue by tmfjr** [lsh123/xmlsec#283]
Following the progression of our code, according to this call stack:

Application.exe!xmlParseCDSect(_xmlParserCtxt * ctxt) Line 9748	C
Application.exe!xmlParseContent(_xmlParserCtxt * ctxt) Line 9831	C
Application.exe!xmlParseInNodeContext(_xmlNode * node, const char * data, int datalen, int options, _xmlNode * * lst) Line 13682	C
Application.exe!xmlSecReplaceNodeBufferAndReturn(_xmlNode * node, const unsigned char * buffer, unsigned int size, _xmlNode * * replaced) Line 632	C
Application.exe!xmlSecReplaceNodeBuffer(_xmlNode * node, const unsigned char * buffer, unsigned int size) Line 609	C
Application.exe!xmlSecEncCtxDecrypt(_xmlSecEncCtx * encCtx, _xmlNode * node) Line 562	C

Inside xmlSecReplaceNodeBufferAndReturn(), xmlParseInNodeContext(node->parent, (const char*)buffer, size, XML_PARSE_NODICT, &results) is called

The call in xmlSecReplaceNodeBufferAndReturn() hard-codes the option to "XML_PARSE_NODICT", and gives us no option to pass in the XML_PARSE_HUGE parameter we need when we call xmlSecEncCtxDecrypt().

Can the option be added to add other "options" when calling xmlSecEncCtxDecrypt() or other top-level functions that call into libxml2? Alternatively a way to specify XML_PARSE_HUGE would be beneficial when decrypting or encrypting large XML files.

thanks,
-Tom

**Comment by lsh123** [comment]
https://github.com/lsh123/xmlsec/pull/284

**Comment by lsh123** [comment]
Fixed in pr #284
