### ISSUE TITLE
configure: --with-libxml with --disable-custom-configs does not work

### ISSUE THREAD

**Issue by dhoeper** [lsh123/xmlsec#288]
https://github.com/lsh123/xmlsec/blob/cd6fe1c19bd40e0e3bd63af61c34d595371e2bc9/configure.ac#L318

This should be `LIBXML_LIB_PATH=...`

**Comment by lsh123** [comment]
Good catch! Thanks.

https://github.com/lsh123/xmlsec/commit/e040111b47c2443b3b96996b711efee756c65d4c
