### ISSUE TITLE
Example verification of documents containing certificates with public key

### ISSUE THREAD

**Issue by rsoeldner** [lsh123/xmlsec#291]
Hello,

Currently struggle to find the equivalent of `xmlsec1 --verify exc-signature.xml ` using the C library. 
I would like to use this peace to verify all available signatures, https://github.com/AnIML/schemas/blob/master/animl-core.xsd#L977 . Do I have to select all `Signature` elements by hand and verify them independently?

I found https://www.aleksey.com/xmlsec/api/xmlsec-xmldsig.html#xmlSecDSigCtxVerify and https://www.aleksey.com/xmlsec/api/xmlsec-keysmngr.html#xmlSecKeysMngr, but how do I receive all available keys and validate all available `Signature`, if they are included?

**Comment by lsh123** [comment]
https://github.com/lsh123/xmlsec/tree/master/examples
