### ISSUE TITLE
xmlSecDSigCtxProcessKeyInfoNode called when optional KeyInfo element not present

### ISSUE THREAD

**Issue by lindsayrea** [lsh123/xmlsec#294]
xmlSecDSigCtxProcessSignatureNode sets keyInfoNode to NULL if the KeyInfo element is not present in the signature, but it does not test for NULL before calling xmlSecDSigCtxProcessKeyInfoNode which then asserts.

**Comment by lsh123** [comment]
Could you please share a repro test case? This is expected since KeyInfo node is optional and xmlSecDSigCtxProcessKeyInfoNode() function itself takes care of it

https://github.com/lsh123/xmlsec/blob/3e24ac3dfff5fe08e4d7510f8b474354fac42646/src/xmldsig.c#L806

**Comment by lsh123** [comment]
no reply for > 6 months
