### ISSUE TITLE
Support stdin in xmlsec1

### ISSUE THREAD

**Issue by OleLaursen** [lsh123/xmlsec#30]
It would be nice if xmlsec1 would support reading from stdin.

I'm currently using xmlsec1 as part of a tool chain written in Python, and it's a bit cumbersome to have to write out a file or resort to shell trickery instead of just piping the input in.

**Comment by lsh123** [comment]
The support for stdin/out was actually there but the code failed earlier due to mix up of "-" with parameter. Fixed https://github.com/lsh123/xmlsec/pull/31

**Comment by lsh123** [comment]
Just an example:

cat ./examples/sign1-res.xml | ./apps/xmlsec1 verify  --pubkey-pem ./examples/rsapub.pem -
