### ISSUE TITLE
with version xmlsec1-1.2.31, Is ECDSA support complete? 

### ISSUE THREAD

**Issue by navigator117** [lsh123/xmlsec#304]
I found XML Security Library Interoperability Report info at:
[https://www.aleksey.com/xmlsec/xmldsig.html](https://www.aleksey.com/xmlsec/xmldsig.html)

int table "Additional XML Security Algorithms (RFC 4051)",  "Features and algorithms", "XMLSec with OpenSSL" ,
ECDSA-SHA1
ECDSA-SHA224
ECDSA-SHA256
ECDSA-SHA384 
ECDSA-SHA512
these algorithms all mark "N", but i can see ECDSA implementations in source code.
So does ECDSA implementations complete or NOT?

BTW, I saw OPENSSL low level function ECDSA_do_sign, ECDSA_do_verify are used, why not use EVP_DigestSign*, EVP_DigestVerify*?

**Comment by lsh123** [comment]
https://github.com/lsh123/xmlsec/pull/315

**Comment by lsh123** [comment]
Fixed, thanks for the bug.
