### ISSUE TITLE
xmlsec-gnutls: reading keys from memory in PEM format not implemented

### ISSUE THREAD

**Issue by jas4711** [lsh123/xmlsec#317]
With the GnuTLS backend, OATH-Toolkit fails to load keys and fails like this:

func=xmlSecGCryptAppKeyLoadMemory:file=app.c:line=236:obj=unknown:subj=unknown:error=9:feature is not implemented:details=xmlSecKeyDataFormatPem
func=xmlSecGCryptAppKeyLoad:file=app.c:line=189:obj=unknown:subj=xmlSecGCryptAppKeyLoadMemory:error=1:xmlsec library function failed:filename=./pskc-ee-key.pem

**Comment by lsh123** [comment]
This should be fixed now. Sorry it took so long but I first needed to migrate the GnuTLS from using GCrypt and that was not a small project.
