### ISSUE TITLE
xmlsec1: undefined symbol: xmlSecCryptoAppKeysMngrCertLoad

### ISSUE THREAD

**Issue by duwenjun** [lsh123/xmlsec#318]
xmlsec1: symbol lookup error: xmlsec1: undefined symbol: xmlSecCryptoAppKeysMngrCertLoad?

any one know how to fix?

**Comment by lsh123** [comment]
How was xmlsec1 compiled?

**Comment by lsh123** [comment]
No response for 6+ months, closing
