### ISSUE TITLE
windows build with debug symbols

### ISSUE THREAD

**Issue by JohnSavage86** [lsh123/xmlsec#329]
In file `win32/Makefile.msvc:423` `LDFLAGS 		= /nologo /debug` present `/debub` argument and in :385, :387` present `/Zi`, that are using for both release and debug bulds. Thus there is no way to build library without debuging information and *.pdb files. Is this a bug or maybe there is some reason for that?

**Comment by lsh123** [comment]
There are so many permutations with flags for building the library. I would recommend tweaking the local version of the makefiles with setting whatever flags you need as a solution (e.g. by having a local patch applied to the xmlsec tree before configuring the build)
