### ISSUE TITLE
Use of OPENSSL_NO_ERR

### ISSUE THREAD

**Issue by bfussell** [lsh123/xmlsec#330]
The code snippet below provides the context for this question. Those APIs are not fully functional if the openssl build uses the configure option no-err. Generally an app such as your would protect the use of those APIs by using #ifndef OPENSSL_NO_ERR. 

Does xmlsec1 support the use of openssl built with no-err ? 
Also, wouldn't using ERR_get_next_error_library() to retrieve the next library code index be safer than hardcoded value XMLSEC_OPENSSL_ERRORS_LIB ?

Thanks.

/* load xmlsec strings in OpenSSL */
    ERR_load_strings(XMLSEC_OPENSSL_ERRORS_LIB, xmlSecOpenSSLStrLib); /* define xmlsec lib name */
    ERR_load_strings(XMLSEC_OPENSSL_ERRORS_LIB, xmlSecOpenSSLStrDefReason); /* define default reason */
    ERR_load_strings(XMLSEC_OPENSSL_ERRORS_LIB, xmlSecOpenSSLStrReasons);

**Comment by lsh123** [comment]
Thanks for the bug report! I've created a PR that should address the issues you reported:

https://github.com/lsh123/xmlsec/pull/331

**Comment by lsh123** [comment]
I believe this should be fixed now. Thanks for the bug report.

**Comment by bfussell** [comment]
Thanks for the quick reply and fix !
