### ISSUE TITLE
xmlsec-openssl3: providers should not be automatically loaded on the default context

### ISSUE THREAD

**Issue by simo5** [lsh123/xmlsec#339]
In the recent PR #334 the library initialization code has been changed to unconditionally load the default and legacy provider.

This is problematic, because these providers are being loaded in the default (NULL) openssl context which is shared with all the users of the context in the application (the application directly and any other library loaded by the application.

The reason why the legacy provider is not loaded by default by openssl is that those algorithms are insecure today. And there are many libraries that handled presence or absence of these algorithms properly by disabling functionality when they are not present.

By loading the legacy provider this way applications that are deemed "secure" because they dynamically avoid insecure algorithms may suddenly start using them lowering their security and with no recourse by the admins, as this is done unconditionally and not through changing the openssl.conf configuration as envisioned by the openssl project.

A similar reasoning can be done for the default provider which should not be forcibly loaded. There are configurations of openssl (like when using the fips provider) where it is intended/legal that the default provider is not loaded.

Loading providers should be either left to the will of admins via openssl.conf, or, if an algorithm is not used for security and/or really is required to provide some key functionality of the library, should be done via creating a separate context for the specific operation.

**Comment by simo5** [comment]
Some examples:
https://github.com/cyrusimap/cyrus-sasl/pull/668/commits/4146861caed69ceebd16531fa12f89b5cb1edfa2
(see init_ossl3_ctx() and how it is used in a specific place only)

**Comment by lsh123** [comment]
Thanks for feedback and pointers. I would like to go in the following direction:
- Global LIB_CTX for LibXMLSEC, can be overwritten by users of the library;
- By default,  LibXMLSEC will create one with default/legacy providers and library users can overwrite it;
- OpenSSL default LIB_CTX is not changed.

WIP PR is here:  https://github.com/lsh123/xmlsec/pull/340

Please let me know what do you think!

**Comment by simo5** [comment]
this is interesting, what algorithms available only in the legacy provider are critical for xmlsec and needs to be always present?

**Comment by lsh123** [comment]
I think RIPEMD160 is the only one but I don't think anybody really cares :)

**Comment by simo5** [comment]
Right, I wonder if the right thing to do is to just allow the application to set the context (so basically most of the changes you have except allocating a new context), but use the NULL context by default.
Then if an application *really* need a legacy algorithm they can set a custom openssl context or indicate to the user that they should enable the legacy provider in openssl.conf so that openssl loads it automatically

**Comment by lsh123** [comment]
My take is that apps should restrict the algorithms that they accept anyway and XMLSec library has provisions to do so. And it actually goes beyond algorithms -- for example XMLEnc 1.0 spec allows  un0encrypted symmetric or private keys do be included into the xml doc. Which completely defeats the purpose :)  No sane app should ever do it or process documents that come in that way. 

However, having this default "all algos" mode is great for testing :)

**Comment by simo5** [comment]
Well I have another reason to ask, and that is this requires apps to explicitly set the context in systems that need to work in fips mode, given fips is a separate provider that is loaded via openssl.conf configuration. But with this code configuration is ignored completely, so enabling the fips provider (or, say, a future pkcs11 provider) now require changing applications.

For testing it is easy to just provide a custom openssl.conf that loads the legacy provider by setting OPENSSL_CONF

**Comment by lsh123** [comment]
It's not as simple since 1) test have no clue which openssl version is used; 2) there are more than openssl library (also nss, gnutls, ...) and tests are also agnostic to that.

But, I hear your point about fips. Let me think about it.

**Comment by lsh123** [comment]
I implemented the solution with custom openssl.cnf for tests and completely removed any overwrites on the providers from xmlsec library itself. I will keep my previous change since I think it might be useful for some use cases to be able to overwrite libctx for xmlsec vs other uses of openssl in the app.

**Comment by simo5** [comment]
I totally agree on keeping the ability to pass in a context, it is invaluable to be able to control the behavior of xmlsec from the application if really desired.

**Comment by lsh123** [comment]
Done (https://github.com/lsh123/xmlsec/issues/341):
- Removed legacy/default provider from code;
- Tests use a dedicated openssl config file (on Linux/Unix);
- App can set dedicated LibCtx for libxmlsec

TODO:
- Ensure that Windows build uses the correct config for tests;
- Add ability for apps to set options flags for provider selection (e.g. "fips=yes");
- (May be) Setup Windows build for openssl3

**Comment by lsh123** [comment]
* Add ability for apps to set options flags for provider selection (e.g. "fips=yes");
This is addressed by OpenSSL already (see EVP_set_default_properties and friends)

* Ensure that Windows build uses the correct config for tests
See PR #342 

* (May be) Setup Windows build for openssl3
See PR #343
