### ISSUE TITLE
openssl v1.1.0-pre5 patch

### ISSUE THREAD

**Issue by symma** [lsh123/xmlsec#34]
Hello,
based on xmlsec1 v1.2.22 release, I've created a patch file concerning openssl v1.1.0-pre5.
please take a look at this and let me known about possible causes/errors in this file.

best regards
hyazinth symma
symma-public@infodas.de

[xmlsec1-1.2.22-openssl-1.1.0-pre5.patch.zip](https://github.com/lsh123/xmlsec/files/300495/xmlsec1-1.2.22-openssl-1.1.0-pre5.patch.zip)

**Comment by lsh123** [comment]
Could you please send a pull request? This is easier way :)

**Comment by symma** [comment]
done

**Comment by lsh123** [comment]
Thank, let's close the ticket and move into the pull request for comments.
