### ISSUE TITLE
xmlsec-openssl3: GOST doesn't have openssl providers yet

### ISSUE THREAD

**Issue by lsh123** [lsh123/xmlsec#341]
From comments on https://github.com/lsh123/xmlsec/pull/340

"First, there are no GOST full-functional providers just now.
Second, engines are still supportable and, if compiled, will work with OpenSSL 3.0 via old interface."

**Comment by lsh123** [comment]
cc @beldmit -- I would greatly appreciate if you can test this since I don't have access to GOST engines:

https://github.com/lsh123/xmlsec/pull/344

**Comment by beldmit** [comment]
https://github.com/gost-engine/engine is the public repo, but I will try to look

**Comment by lsh123** [comment]
Thanks! I got it working and my PR works as expected. Side note -- I built openssl-1.1.1 branch against OpenSSL 3.0 and I had major issues with lib64 for OpenSSL (vs lib for older versions). I had to create a symlink at the end. I'll file an issue for you.
