### ISSUE TITLE
Not compiling under windows

### ISSUE THREAD

**Issue by tpecholt** [lsh123/xmlsec#38]
I used win32/configure.js to generate makefile. When I run it in VS2015 command prompt I get an error: 
..\src\xmlsec.c(113): error C2065: 'XMLSEC_DEFAULT_CRYPTO': undeclared identifier

I found out the generated makefile doesn't use $(APP_CFLAGS) for source files in XMLSEC_SRCDIR folder. Adding it there solves this issue. I think it should be fixed in the repo.

**Comment by tpecholt** [comment]
OK it seems there are more issues - XMLSEC_NO_GOST2012, evp_signatures.c is not linking etc.

**Comment by lsh123** [comment]
It was already fixed in the master:

https://github.com/lsh123/xmlsec/pull/37
