### ISSUE TITLE
SystemError: null argument to internal routine

### ISSUE THREAD

**Issue by NiklasRoberts** [lsh123/xmlsec#404]
When attempting to run pytest, all lines containing `import xmlsec` error out with `SystemError: null argument to internal routine`. 

Versions:
- xmlsec=1.3.3
- libxmlsec1=1.2.34
- libxml2 (unrelated?)=2.9.14

Run on macOS 11.6.7

**Comment by lsh123** [comment]
I know nothing about Python bindings for xmlsec but I would start debugging the problem from checking that all shared libraries can be loaded correctly (LD_LIBRARY_PATH and LTDL_LIBRARY_PATH). If this doesn't help, then please reach out to Python XMLSec maintainers (https://pypi.org/project/xmlsec/).
