### ISSUE TITLE
nss and gcrypt test failure in 1.2.35

### ISSUE THREAD

**Issue by andyrtr** [lsh123/xmlsec#415]
new version 1.2.35 fails in xmlsec-nss tests here (Arch Linux / nss 3.84 - last release 1.2.34 is still passing all test):

```
--- testKeys started for xmlsec-nss library (20221025_091455) ---
--- LD_LIBRARY_PATH=/build/xmlsec/src/xmlsec1-1.2.35/src/.libs:
--- LTDL_LIBRARY_PATH=/build/xmlsec/src/xmlsec1-1.2.35/src/gnutls/.libs:/build/xmlsec/src/xmlsec1-1.2.35/src/gcrypt/.libs:/build/xmlsec/src/xmlsec1-1.2.35/src/nss/.libs:/build/xmlsec/src/xmlsec1-1.2.35/src/openssl/.libs:
Test: hmac-192 (success)
 /build/xmlsec/src/xmlsec1-1.2.35/apps/xmlsec1 check-key-data  --crypto nss --crypto-config /tmp/xmlsec-crypto-config hmac
func=xmlSecNssAppInit:file=app.c:line=86:obj=unknown:subj=NSS_InitReadWrite:error=4:crypto library function failed:config=/tmp/xmlsec-crypto-config; NSS error: -8015
Error: xmlSecCryptoAppInit failed
Error: xmlsec crypto intialization failed.
Error: initialization failed
Unknown command
func=xmlSecNssAppShutdown:file=app.c:line=137:obj=unknown:subj=NSS_Shutdown:error=4:crypto library function failed:NSS error: -8038
Error: xmlSecCryptoAppShutdown failed
Error: xmlsec crypto shutdown failed.
```
I can't find any further test log file.

**Comment by lsh123** [comment]
What version of NSS do you have installed? The error indicates that nss can't open the keys database for some reasons.

**Comment by lsh123** [comment]
Any chance you can try this PR?

https://github.com/lsh123/xmlsec/pull/418

The error indicates that nss can't open certs/keys database. It used to be that NSS didn't like empty database folder and I had an old empty DB there instead. I don't believe I need it anymore.

**Comment by lsh123** [comment]
I will have a new release early next week to update docs for retiring xmlsec mailing list (https://www.aleksey.com/pipermail/xmlsec/2022/010496.html), this fix will be included.

**Comment by andyrtr** [comment]
After applying it keeps failing in a similar way here:
```
/build/xmlsec/src/xmlsec1-1.2.35/apps/xmlsec1 check-key-data  --crypto gcrypt --crypto-config /tmp/xmlsec-crypto-config hmac
func=xmlSecGCryptAppInit:file=app.c:line=99:obj=unknown:subj=gcry_control(GCRYCTL_INIT_SECMEM):error=4:crypto library function failed:gcrypt error: 16777217: gcrypt: General error
Error: xmlSecCryptoAppInit failed
Error: xmlsec crypto intialization failed.
Error: initialization failed
Unknown command
Usage: xmlsec <command> [<options>] [<files>]
```

**Comment by lsh123** [comment]
argh

**Comment by lsh123** [comment]
But did nss tests pass? This looks like gcrypt error now -- which version of libgcrypt do you have installed?

**Comment by andyrtr** [comment]
libgcrypt 1.10.1

**Comment by andyrtr** [comment]
[xmlsec-1.2.35-1-x86_64-check.log](https://github.com/lsh123/xmlsec/files/9861319/xmlsec-1.2.35-1-x86_64-check.log)

**Comment by lsh123** [comment]
Thanks, there is no easy way to disable tests unless you want to disable gcrypt all together. Can you try suggestions from the bug above? Not sure if it is possible to modify libgcrypt as described here:

**Comment by lsh123** [comment]
The only other suggestion I have --> I can ignore the error returned by gcry_control(GCRYCTL_INIT_SECMEM), this might not be the correct thing to do though.

**Comment by andyrtr** [comment]
For now at packaging level I will proceed after the test failure to finish building the package.

**Comment by lsh123** [comment]
Hm.. not sure this is the right way either. I looked through the code and libgcrypt itself ignores the error from gcry_control(GCRYCTL_INIT_SECMEM). Let me do the same, I should have another release early next week to update docs for retiring mailing list. You might want to wait until then and just package new release (1.2.36).
