### ISSUE TITLE
xmlsec hardcodes PKG_CONFIG="pkg-config" instead of using the environment variable $PKG_CONFIG

### ISSUE THREAD

**Issue by tgurr** [lsh123/xmlsec#42]
This results in build failures on cross environments where the pkg-config command may be prefixed with the host triplet, e.g. x86_64-pc-linux-gnu-pkg-config.

It should be possible to specify $PKG_CONFIG and if not set it should fall back to pkg-config by default.

**Comment by lsh123** [comment]
Switched to use PKG_PROG_PKG_CONFIG instead: https://github.com/lsh123/xmlsec/pull/47
