### ISSUE TITLE
xmlsec does not export inlcude/xmlsec/openssl include files when building static libraries on windows

### ISSUE THREAD

**Issue by jefmason** [lsh123/xmlsec#420]
The win32/Makefile.msvc does not have targets under the 'install' rule to release C/C++ .h header files for include/xmlsec/openssl when building only static libraries.   I added two new targets for 'if exist $(BINDIR)\$(XMLSEC_OPENSSL_A)' to create the directory and populate it.  These are identical to the targets for 'if exist $(BINDIR)\$(XMLSEC_OPENSSL_SO)' with the library name change.  There might be other places such as uninstall that need similar changes.  
[Makefile.zip](https://github.com/lsh123/xmlsec/files/9863813/Makefile.zip)

**Comment by lsh123** [comment]
Thanks for bug report and the proposed fix! The PR #421 should address the issue not only for openssl but for all other crypto libraries. I will have a new release early next week to update docs for retiring xmlsec mailing list (https://www.aleksey.com/pipermail/xmlsec/2022/010496.html), this fix will be included.
