### ISSUE TITLE
xmlsec-openssl 1_2_36: xmlSecOpenSSLRsaPkcs1Process not returning an error.

### ISSUE THREAD

**Issue by scaro-axway** [lsh123/xmlsec#449]
Hi,

While testing an XML multi-recipient decryption with OpenSSL 3, I came across an issue: function "xmlSecEncCtxDecrypt" is not returning an error while the error callback is displaying decryption errors.

Digging into the issue lead to [kt_rsa.cpp: 528](https://github.com/lsh123/xmlsec/blob/8b0a46fb9e8dbe429caf26748c9f1848608df420/src/openssl/kt_rsa.c#L528), it looks like there is a "return (-1);" missing.
The same issue exists on master.

**Comment by lsh123** [comment]
Argh... PR #450. I will try to do a 1.2.37 release asap

Thanks for report and investigation on the root cause!

**Comment by lsh123** [comment]
I did full audit and found one place. Thanks again for bug report.

**Comment by lsh123** [comment]
The fix is included in the 1.2.37 release (https://github.com/lsh123/xmlsec/discussions/452)
