### ISSUE TITLE
libxmlsec1-gnutls needs direct link against libgcrypt

### ISSUE THREAD

**Issue by dmacks** [lsh123/xmlsec#466]
I add ```-no-undefined``` when building on OS X to make sure my shared-libraries will have all symbols resolved at load-time. Doing so gives a bunch of compile-time failures at the linking stage, due to unresolved _gcry_* symbols. Looking at src/gnutls/Makefile.am, I see ```libxmlsec1_gnutls_la_CPPFLAGS = ... $(GCRYPT_CFLAGS)```, which is consistent with xmlsec-gcrypt making direct use of gcrypt at compile-time. There is a note:
```
# xmlsec-gnutls library requires xmlsec-gcrypt                                                              
libxmlsec1_gnutls_la_LIBADD = \
[...]
       ../gcrypt/libxmlsec1-gcrypt.la \
```
and of course libxmlsec1-gcrypt does link against libcrypt, but my linker does not follow indirect dependencies to resolve symbols, thanks to "two-level namespace" behavior. Instead, if a lib uses symbols from another lib, it needs to link against it explicitly. To fix, just need to add the analogous library $(GCRYPT_LIBS) to the _LIBADD here. This is logically sane and shouldn't cause problems for others.

**Comment by lsh123** [comment]
Thanks, could you please confirm that PR #468 fixes it for you?

**Comment by dmacks** [comment]
Seems like it. Thanks!

**Comment by lsh123** [comment]
Great!
