### ISSUE TITLE
xmlSecDSigCtxProcessKeyInfoNode 45

### ISSUE THREAD

**Issue by fingermark** [lsh123/xmlsec#53]
What does this error mean?

I get it using `dm.xmlsec.binding` trying to verify XML using this library:  https://github.com/onelogin/python-saml/blob/master/src/onelogin/saml2/utils.py#L1075

```
xmldsig.c:871(xmlSecDSigCtxProcessKeyInfoNode) errno=45
xmldsig.c:565(xmlSecDSigCtxProcessSignatureNode) subject=xmlSecDSigCtxProcessKeyInfoNode
xmldsig.c:366(xmlSecDSigCtxVerify) subject=xmlSecDSigCtxSignatureProcessNode
```

**Comment by lsh123** [comment]
#define XMLSEC_ERRORS_R_KEY_NOT_FOUND 45
