### ISSUE TITLE
Support for Apple CoreCrypto library for iOS and macOS support

### ISSUE THREAD

**Issue by rickmark** [lsh123/xmlsec#549]
A new backend cryptographic provider should be implemented for the Apple CoreCrypto libraries to allow for digital signature on iOS

**Comment by lsh123** [comment]
Thanks for the suggestion! This might a bit of work though and I am not sure if I get to it soon. But I gladly accept patches :)

**Comment by lsh123** [comment]
BTW, you can get OpenSSL to work on iOS:

https://github.com/krzyzanowskim/OpenSSL

And then you will have access to all the XMLSec features right away.

**Comment by lsh123** [comment]
I am going to close this one:
- Apple CoreCrypto library is very limited and supports very small subset of  crypto operations
- There is a workaround with using openssl on iOS / Mac
