### ISSUE TITLE
autodetection of libcrypto on Solaris 11

### ISSUE THREAD

**Issue by jamesharris9999** [lsh123/xmlsec#56]
in configure.ac line - 467 the script is looking for libcrypto.a in the specified library directories. On Solaris 11 with openssl installed by pkg, this file does not exist. 

Can this reference be changed to libcypto.so, which resolves this issue?

Ideally this would be resolved by installing a version of libssl-dev on solaris 11, however I have been unable to locate this package at http://pkg.oracle.com/

**Comment by lsh123** [comment]
Unfortunately this might not work correctly on other platforms if .so and .a are in different folders (and we need .a).

**Comment by lsh123** [comment]
I believe you need to install libssl_dev package (https://www.opencsw.org/search/libssl_dev/) which would install .pc files that would be used by xmlsec configure.ac (around line 418).
