### ISSUE TITLE
Is ecdsa-ripemd160 supported

### ISSUE THREAD

**Issue by timlegge** [lsh123/xmlsec#562]
Hi

Not really a request to get it supported.  I have an exception in my test scripts that said it was not supported by xmlsec.  Just checking in to see if that changed.

Tim

**Comment by lsh123** [comment]
Yea, I didn't bother since I don't know anybody using ripemd160 these days. If someone asks, then I can easily add it. Just everyone is using sha2 or sha3 anyway.

**Comment by lsh123** [comment]
BTW, you might find these two pages interesting (will be on the website in the next release):

https://github.com/lsh123/xmlsec/blob/master/docs/xmldsig.html
https://github.com/lsh123/xmlsec/blob/master/docs/xmlenc.html

**Comment by timlegge** [comment]
Thanks.  I knew that the latest versions had some updates

**Comment by lsh123** [comment]
The main point is that the tables have been updated and reflect all supported features correctly now :) It's hard to see on github but you can open the html files locally if you pull it from github first.

**Comment by lsh123** [comment]
Never mind -- I actually implemented ECDSA-RIPEMD160 for OpenSSL. Let me know if you have any problems with it :) 

https://github.com/lsh123/xmlsec/blob/master/tests/aleksey-xmldsig-01/enveloped-ripemd160-ecdsa-ripemd160.xml

**Comment by timlegge** [comment]
Hi @lsh123 

I tested the changes and had an issue until I realised that you had specified:

<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-ripemd160"/>

I can't find a reference to ecdsa-ripemd160 in that version.  The earliest I could find was 

 http://www.w3.org/2007/05/xmldsig-more#ecdsa-ripemd160

Tim

**Comment by lsh123** [comment]
Argh... you are absolutely correct: 

https://www.ietf.org/rfc/rfc9231.html#name-ecdsa-sha-ecdsa-ripemd160-e

Thank you for catching it! this why I love to have test vectors :) I will it shortly.

**Comment by lsh123** [comment]
Fixed, thanks again for bug report!

**Comment by timlegge** [comment]
That seems to work fine.  Thanks
