### ISSUE TITLE
xmlsec1 cli: signing with ECDSA, the KeyValue is failed

### ISSUE THREAD

**Issue by adomjan** [lsh123/xmlsec#610]
xmlsec1 sign --crypto openssl --pkcs12 key.p12 --pwd xxx request.xml

If request.xml contain:

<KeyInfo>
  <KeyValue/>
<KeyInfo/>

 the signing will fail:

func=xmlSecKeyDataXmlWrite:file=keysdata.c:line=295:obj=unknown:subj=id->xmlWrite != NULL:error=100:assertion: 
func=xmlSecKeyDataValueXmlWrite:file=keyinfo.c:line=926:obj=key-value:subj=xmlSecKeyDataXmlWrite:error=1:xmlsec library function failed:node=ECDSAKeyValue
func=xmlSecKeyInfoNodeWrite:file=keyinfo.c:line=186:obj=key-value:subj=xmlSecKeyDataXmlWrite:error=1:xmlsec library function failed:node=KeyValue
func=xmlSecDSigCtxProcessKeyInfoNode:file=xmldsig.c:line=816:obj=unknown:subj=xmlSecKeyInfoNodeWrite:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=514:obj=unknown:subj=xmlSecDSigCtxProcessKeyInfoNode:error=1:xmlsec library function failed: 
func=xmlSecDSigCtxSign:file=xmldsig.c:line=296:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature failed 

with RSA key, the signing works.

**Comment by lsh123** [comment]
Could you please share your template in the request.xml?

**Comment by adomjan** [comment]
[request.zip](https://github.com/lsh123/xmlsec/files/11021694/request.zip)

here is

**Comment by lsh123** [comment]
Which version of xmlsec are you using? This is what I get with the current master:

```
$ ./apps/xmlsec1 sign --pkcs12 tests/keys/ec-prime256v1-key.p12 --pwd secret123 --lax-key-search --output request-out.xml request.xml 
Signature status: OK
```

The ECKeyValue support was added about a month ago in PR #517 so if you are using the previous versions of xmlsec then the error you get is not unexpected :)

**Comment by adomjan** [comment]
1.2.37
OK I will try master

**Comment by adomjan** [comment]
It works fine with the master, sorry for bothering you.

**Comment by lsh123** [comment]
Not a problem at all! Glad you figured it out! I should have a release by mid April that would (of course) have ECKeyValue supported.
