### ISSUE TITLE
xmlSecNssGetInternalKeySlot function arguments missing

### ISSUE THREAD

**Issue by ryandesign** [lsh123/xmlsec#627]
Building xmlsec 1.3.0 with clang 15 fails:

```
crypto.c:415:28: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
xmlSecNssGetInternalKeySlot()
                           ^
                            void
1 error generated.
make[3]: *** [libxmlsec1_nss_la-crypto.lo] Error 1 
```

The problem is that you haven't declared `xmlSecNssGetInternalKeySlot`'s arguments:

https://github.com/lsh123/xmlsec/blob/72969909da80121da804c4e89d9e74dee3576000/src/nss/crypto.c#L414-L415

If this is to be a function that takes no arguments, you must declare it as such:

```diff
--- src/nss/crypto.c.orig	2023-04-12 11:45:12.000000000 -0500
+++ src/nss/crypto.c	2023-04-13 02:05:19.000000000 -0500
@@ -412,7 +412,7 @@
  * Returns: internal key slot and initializes it if needed.
  */
 PK11SlotInfo *
-xmlSecNssGetInternalKeySlot()
+xmlSecNssGetInternalKeySlot(void)
 {
     PK11SlotInfo *slot = NULL;
     SECStatus rv;
```

This was reported to MacPorts here: https://trac.macports.org/ticket/67227

**Comment by lsh123** [comment]
Thanks, I wonder why macosx build in github actions didn't catch it.

**Comment by ryandesign** [comment]
> I wonder why macosx build in github actions didn't catch it.

Xcode 14.3 is the first version whose clang is based on clang 15. Xcode 14.3 requires macOS 13 or later. Your GitHub Actions configuration file uses macOS 12. GitHub Actions does not have a macOS 13 runner yet; see https://github.com/actions/runner-images/issues/6426.

**Comment by lsh123** [comment]
thanks for looking into it! I will switch to the mac-13 as soon as it is available!

**Comment by ryandesign** [comment]
FYI it's [available now](https://github.blog/changelog/2023-04-24-github-actions-macos-13-is-now-available/).

**Comment by lsh123** [comment]
Thanks, PR #651
