### ISSUE TITLE
1.3.0 sign without inserting KeyName

### ISSUE THREAD

**Issue by ojii** [lsh123/xmlsec#631]
In 1.3.0, is it possible to use the `xmlsec1` command line tool to sign a document without inserting the `KeyName` into the `KeyInfo` element?

**Comment by lsh123** [comment]
You might find this note from the [release notes](https://github.com/lsh123/xmlsec/discussions/623) helpful:

> (API breaking change) Changed the key search to strict mode: only keys referenced by KeyInfo are used. To restore the old "lax" mode, set XMLSEC_KEYINFO_FLAGS_LAX_KEY_SEARCH flag on xmlSecKeyInfoCtx or use '--lax-key-search' option for XMLSec command line utility.

Said that, I would not recommend to do this: the old "lax" key search model where key is looked up by "key type" (e.g. RSA key) can lead to unexpected surprises if your application has more than one key. By using KeyName (or [X509Digest](https://www.w3.org/TR/xmldsig-core1/#sec-X509Data), or other key selectors), there is no confusion which key will be used.

**Comment by ojii** [comment]
I always pass an explicit key to xmlsec, so I do not need key search. I know i can use `--lax-key-search` to make verifying work, but I would like to know how to not include the keyname element when signing documents.

**Comment by lsh123** [comment]
If you don't add KeyName element to the template then it will not be in the final document
