### ISSUE TITLE
xmlSecOpenSSLTransformGost2001GostR3411_94GetKlass() missing from xmlsec 1.3.0

### ISSUE THREAD

**Issue by ralfjunker** [lsh123/xmlsec#632]
Commit https://github.com/lsh123/xmlsec/commit/5e06ee0d950304b31155f7aea3c0c2d6777fa853 removed ``xmlSecOpenSSLTransformGost2001GostR3411_94GetKlass()``:

Nevertheless, ``xmlSecOpenSSLTransformGost2001GostR3411_94GetKlass():`` is still referenced here: https://github.com/lsh123/xmlsec/blob/master/src/openssl/crypto.c#L245

As a result, XMLSec 1.3.0 with OpenSSL requires ``-DXMLSEC_NO_GOST=1`` to compile.

Could this be fixed?

**Comment by lsh123** [comment]
Argh, typo (it was moved to another file):

https://github.com/lsh123/xmlsec/commit/5e06ee0d950304b31155f7aea3c0c2d6777fa853#diff-cb9a3c77ca8bff63b1ae75c45bcea0d96a056fe3a85d33eed815a0aaa3c4908bR2191

I will fix it shortly

**Comment by lsh123** [comment]
Should be fixed on master
