### ISSUE TITLE
examples/verify2.c: xmlSecCryptoAppKeyLoad vs. xmlSecCryptoAppKeyLoadEx oversight

### ISSUE THREAD

**Issue by ralfjunker** [lsh123/xmlsec#634]
``xmlSecCryptoAppKeyLoad`` should be ``xmlSecCryptoAppKeyLoadEx`` (missing ``...Ex`` suffix): https://github.com/lsh123/xmlsec/blob/master/examples/verify2.c#L188

Probably oversight from https://github.com/lsh123/xmlsec/commit/e47ea7010e1d7bbfd97d8a8fd8006b89245a88c5.

**Comment by lsh123** [comment]
thanks, should be fixed on master
