### ISSUE TITLE
xmlsec-mscng: remove CERT_CLOSE_STORE_CHECK_FLAG from release

### ISSUE THREAD

**Issue by postboy** [lsh123/xmlsec#650]
As far as I can see, after all previous commits there should be no leaks regarding ctx->trusted, ctx->untrusted, ctx->trustedMemStore, ctx->untrustedMemStore. CERT_CLOSE_STORE_CHECK_FLAG becomes useless, and documentation advices against it's usage in production.

We briefly discussed this in https://github.com/lsh123/xmlsec/issues/638. @lsh123 and @vmiklos both said that it would be perfect if CERT_CLOSE_STORE_CHECK_FLAG would stay in debug and would be removed in release. I don't know how to achieve that. I didn't found anything by "DEBUG" substring in source files.

I will be glad if someone else will do this small task :)

**Comment by postboy** [comment]
As an idea, of course those flags can be completely removed from repository.

**Comment by lsh123** [comment]
See PR #657

**Comment by lsh123** [comment]
it's trivial :)
