### ISSUE TITLE
Support for LibreSSL is broken in 1.3.x

### ISSUE THREAD

**Issue by lsh123** [lsh123/xmlsec#665]
From discussion in PR #654 

The remaining issues with LibreSSL 3.8.0 that I see with make -k are:

* The openssl/store.h include is missing.
```
    [xmlsec/src/openssl/app.c](https://github.com/lsh123/xmlsec/blob/4c7500252f20170f379081abccb750f0840407f4/src/openssl/app.c#L47)

    Line 47 in [4c75002](https://github.com/lsh123/xmlsec/commit/4c7500252f20170f379081abccb750f0840407f4)

 #include <openssl/store.h> 
```

* The EVP_PKEY_DHX define is missing.

```
[xmlsec/src/openssl/evp.c](https://github.com/lsh123/xmlsec/blob/4c7500252f20170f379081abccb750f0840407f4/src/openssl/evp.c#L317)

Line 317 in [4c75002](https://github.com/lsh123/xmlsec/commit/4c7500252f20170f379081abccb750f0840407f4)
 case EVP_PKEY_DHX: 
```

* Several sk_X509_* functions are missing.
```
[xmlsec/src/openssl/x509.c](https://github.com/lsh123/xmlsec/blob/4c7500252f20170f379081abccb750f0840407f4/src/openssl/x509.c#L556)

Line 556 in [4c75002](https://github.com/lsh123/xmlsec/commit/4c7500252f20170f379081abccb750f0840407f4)

     ctxDst->certsList = sk_X509_deep_copy(ctxSrc->certsList, (sk_X509_copyfunc)X509_dup, X509_free); 

```

**Comment by lsh123** [comment]
See PR #666 

Remaining issues:
- The keys test fails since store keys support is disabled (not sure how to handle it)
- One of the xmldsig tests fails with "EE certificate key too weak" error (need to upgrade keys?)

**Comment by lsh123** [comment]
cc @orbea

**Comment by lsh123** [comment]
Tests fixed as well.

**Comment by orbea** [comment]
@lsh123 Thank you very much for doing this, I have been juggling a lot of unrelated responsibilities the last few days. You probably would have a better idea how to do this anyways. :)

**Comment by lsh123** [comment]
@orbea not a problem! it was trivial as you can see from the diff
