### ISSUE TITLE
Missing encoding in output xml

### ISSUE THREAD

**Issue by tyctor** [lsh123/xmlsec#684]
hi

i am using `xmlsec` with `pysaml2`
in xml output header there is no encoding attribute

just 
`<?xml version="1.0"?>`

is there some option that will add `encoding`?
`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by lsh123** [comment]
Xmlsec library will use whatever is provided in the template. There are many examples in the `tests` folder, e.g.:
- output: https://github.com/lsh123/xmlsec/blob/master/tests/aleksey-xmldsig-01/dtd-hmac-91.xml
- templates https://github.com/lsh123/xmlsec/blob/master/tests/aleksey-xmldsig-01/dtd-hmac-91.tmpl

If this doesn’t help, I recommend to file a bug against Python bindings for xmlsec.

Best, 
Aleksey

**Comment by tyctor** [comment]
thanks for your reply

is there some way how to ommit xml declaration from output (not include it if source xml doesnt have it)

**Comment by lsh123** [comment]
Not with the xmlsec command line tool. But in your code, you can write the node (instead of the doc) out like this:

https://stackoverflow.com/questions/25410366/libxml2-avoid-xml-version
