### ISSUE TITLE
Test script does 'rm -rf /*' on ubuntu

### ISSUE THREAD

**Issue by blackbearman** [lsh123/xmlsec#714]
When tests/testKeys.sh script is running it doesn't check the directory that he have to delete.
So, `rm -rf $crypto_config_folder/*` turns to `rm -rf /*` because $crypto_config_folder is not set in this script.

It deleted all files in ~ in my case. Only good point that I pushed all commits BEFORE testing.

**Comment by lsh123** [comment]
It is set here:

https://github.com/lsh123/xmlsec/blob/9b0821762a32e67077dd3fd76187550aae60d3f4/tests/testrun.sh#L69

```
crypto_config_folder=$TMPFOLDER/xmlsec-crypto-config
```

And TMPFOLDER is set here:

https://github.com/lsh123/xmlsec/blob/9b0821762a32e67077dd3fd76187550aae60d3f4/tests/testrun.sh#L28


The testKeys.sh was never intended to be run standalone:

https://github.com/lsh123/xmlsec/blob/9b0821762a32e67077dd3fd76187550aae60d3f4/tests/testKeys.sh#L3
```
# This script needs to be called from testrun.sh script
```
