### ISSUE TITLE
Error encrypting after upgrading

### ISSUE THREAD

**Issue by arj03** [lsh123/xmlsec#731]
Hi

First of all thanks for your continuous support of this library. It's great to see it updated to the latest encryption standards. 

I'm trying to encrypt using RSA OAEP so I had to compile a version myself to test it out. First of all I wanted to check if my compile was ok so I found a template file here for testing: https://users.dcc.uchile.cl/~pcamacho/tutorial/web/xmlsec/session-key-template.xml. I saved that file as basic-encryption.xml. Running this command works fine with the version from ubuntu (1.2.7):

```
xmlsec1 --encrypt --pubkey-cert-pem server-cert.pem --session-key des-192 --binary-data ltmain.sh --output res.xml basic-encryption.xml
```

But if I run it with my self-compiled version I get the following error:

```
./install/bin/xmlsec1 --encrypt --pubkey-cert-pem server-cert.pem --session-key des-192 --binary-data ltmain.sh --output res.xml --verbose basic-encryption.xml

func=xmlSecKeysMngrGetKey:file=keys.c:line=1347:obj=unknown:subj=unknown:error=45:key is not found:details=NULL
func=xmlSecEncCtxEncDataNodeRead:file=xmlenc.c:line=793:obj=unknown:subj=unknown:error=45:key is not found:encMethod=rsa-1_5
func=xmlSecEncCtxBinaryEncrypt:file=xmlenc.c:line=311:obj=unknown:subj=xmlSecEncCtxEncDataNodeRead:error=1:xmlsec library function failed: 
func=xmlSecKeyDataEncryptedKeyXmlWrite:file=keyinfo.c:line=1704:obj=enc-key:subj=xmlSecEncCtxBinaryEncrypt:error=1:xmlsec library function failed: 
func=xmlSecKeyInfoNodeWrite:file=keyinfo.c:line=184:obj=enc-key:subj=xmlSecKeyDataXmlWrite:error=1:xmlsec library function failed:node=EncryptedKey
func=xmlSecEncCtxEncDataNodeWrite:file=xmlenc.c:line=852:obj=unknown:subj=xmlSecKeyInfoNodeWrite:error=1:xmlsec library function failed: 
func=xmlSecEncCtxUriEncrypt:file=xmlenc.c:line=512:obj=unknown:subj=xmlSecEncCtxEncDataNodeWrite:error=1:xmlsec library function failed: 
Error: failed to encrypt file "ltmain.sh"
Error: failed to encrypt file with template "basic-encryption.xml"
```

Thanks in advance for your time.

**Comment by lsh123** [comment]
Can you try this?

https://github.com/lsh123/xmlsec/discussions/623

> (API breaking change) Changed the key search to strict mode: only keys referenced by KeyInfo are used. To restore
> the old "lax" mode, set XMLSEC_KEYINFO_FLAGS_LAX_KEY_SEARCH flag on xmlSecKeyInfoCtx or use
> '--lax-key-search' option for XMLSec command line utility.

**Comment by arj03** [comment]
That works. Thanks!

**Comment by lsh123** [comment]
Great to hear! please consider changing your code to avoid using "lax key search" mode. I disabled it by default because it opens up a potential security vulnerability with attacker "substituting" the keys.
