### ISSUE TITLE
Empty X509SubjectName

### ISSUE THREAD

**Issue by lampaczcz** [lsh123/xmlsec#761]
After upgrade from Debian 8 to Debian 12, xmlsec1 (what program calls in Debian) stop filling X509Data -> X509SubjectName
                <ds:KeyInfo>
                        <ds:X509Data>
                                <ds:X509SubjectName/>
                                <ds:X509Certificate/>
                        </ds:X509Data>
                </ds:KeyInfo>

Fills only X509Certificate, X509SubjectName is empty. When template contains only X509SubjectName is filled but not both

xmlsec1 1.2.37 (openssl)

On Debian testing is version xmlsec1 1.2.38 (openssl) and is working OK

**Comment by lsh123** [comment]
Can you share the template that you use? And also xmlsec version number?

**Comment by lsh123** [comment]
Actually never mind, this was fixed in 1.2.38 indeed:

https://github.com/lsh123/xmlsec/commit/c4529d3661278aa1b4657d03406871bae3aa9f12
