### ISSUE TITLE
Could Semver be applied in xmlsec?

### ISSUE THREAD

**Issue by deronnax** [lsh123/xmlsec#769]
Hello. I would like to report that xmlsec removed support for some stuff in xmlsec 1.3.3, which significantly broke python-xmlsec. 
[Semver](https://semver.org/) mandates that breaking changes be a major version upgrade and no breaking changes happen in minor/patch version bump.
Could Semver be applied for future changes?
Thank you very much?

**Comment by deronnax** [comment]
OK but though, the removal should have been done in the 1.2.x -> 1.3.x bump. Everybody assume a patch update won't do major breakage. It's painful even for linux distribution maintainer would did nothing wrong.

**Comment by deronnax** [comment]
Sorry to insist, I don't mean to be rude or unpleasant, but, unless I am mistaking, commit 114f580409e076bbe7b352eb74008d818c6e3e93, which has been made between 1.3.2 and 1.3.3, removes functions, among other things `xmlSecCryptoAppKeyLoad`, which broke python-xmlsec.

**Comment by lsh123** [comment]
Ah sorry, I thought you are talking about soap stuff. I'll keep this in mind, but in general I feel that several years of marked as "deprecated" should be good enough warning.

**Comment by deronnax** [comment]
Sure, but both are valid:  several years of marked as "deprecated" is a good reason to remove stuff, but it should still be done with at least a minor (major should be the way to go but some people don't like this because it doesn't feel enough of a change but that's OK if you are on the "minor bump" team) :) 
Thank you for your time.
