### ISSUE TITLE
ETA on the next release

### ISSUE THREAD

**Issue by mxamin** [lsh123/xmlsec#770]
I'm a collaborator of [python-xmlsec](https://github.com/xmlsec/python-xmlsec) and we're trying to release a new version which is gonna be compatible with the latest version of xmlsec library but we can not do that because of the typo that was fixed after releasing v1.3.3: https://github.com/lsh123/xmlsec/pull/755
I wonder if there is an ETA on the next release so we can plan our release accordingly.

**Comment by lsh123** [comment]
Let me do an RC build today and then I will release it in ~2 weeks

**Comment by lsh123** [comment]
The1.3.4 release is out: https://github.com/lsh123/xmlsec/releases/tag/1.3.4
