### ISSUE TITLE
xmlSecDSigCtxDebugDump Access Violation

### ISSUE THREAD

**Issue by hafedh-trimeche** [lsh123/xmlsec#800]
Hello,

Please note this issue posted on VCPKG

https://github.com/microsoft/vcpkg/issues/34932

It seams that is the cause the AV.

Best regards.

**Comment by lsh123** [comment]
I'll repeat my opinion from the other bug: I believe it's one of the two things:
* mismatch in the C runtime for various libraries (xmlsec, libxml2, libxslt, openssl, ... )
* mismatch between compiled and loaded libraries (i.e. library versions, compilation flags, etc are not the same)

>  It seams that the library doesn't check some null values before dumping related content.

Please feel free to review the code and point out any issues with no checks for null values:

https://github.com/lsh123/xmlsec/blob/243afff94c6eb468bec96e9637e0f1c6fe6da445/src/xmldsig.c#L1035

**Comment by lsh123** [comment]
BTW if you can reproduce the issue with xmlsec command line utility then it would be easier to debug it.  Use ```--print-debug``` flag to trigger xmlSecDSigCtxDebugDump usage

**Comment by lsh123** [comment]
oh I missed it: "I used fopen and fclose function statically linked to open and close Log file". Of course this is going to crash. Welcome to Microsoft runtimes hell. Question 2.7 in the FAQ (https://www.aleksey.com/xmlsec/faq.html).
