### ISSUE TITLE
Memory leak in xmlSecOpenSSLCreateReadFileBio()

### ISSUE THREAD

**Issue by ralfjunker** [lsh123/xmlsec#802]
A file not found results in a memory leak here: https://github.com/lsh123/xmlsec/blob/548c71e56cd1adc85c14c25941451fbc1ceb9230/src/openssl/crypto.c#L774-L778

`BIO_free(bio);` is missing to free the BIO and its associated resources.

**Comment by ralfjunker** [comment]
If `BIO_read_filename()` fails, `xmlSecOpenSSLCreateReadFileBio()` returns `NULL` and the caller has nothing to free.

To reproduce, call `xmlSecCryptoAppKeysMngrCertLoad()` with a filename of a file which does not exist.

**Comment by lsh123** [comment]
argh, thanks --missed it

https://github.com/lsh123/xmlsec/pull/803
