### ISSUE TITLE
xmlsec assumes a const object has only one address

### ISSUE THREAD

**Issue by jmossber-vc** [lsh123/xmlsec#805]
in xmlsec we see constructions like this one, where the address of a const object is used as its ID.

```c
typedef const struct _xmlSecTransformKlass              xmlSecTransformKlass,
                                                        *xmlSecTransformId;
``` 

This is not good as the compiler/linker can create multiple copies of a const object, so there could be multiple IDs for the same thing.

This can probably cause multiple problems, but the one I've seen is that an allowed reference transform was denied because the ID used when allowing it did not match the ID used when parsing the document, even though it was the same transform.

I use the attached patch as a workaround, which just removes the const from these cases. Had to compress it to be able to attach it, sorry for the inconvenience.

[0001-Don-t-use-the-address-of-a-const-object-as-its-ID.zip](https://github.com/user-attachments/files/16142727/0001-Don-t-use-the-address-of-a-const-object-as-its-ID.zip)

**Comment by lsh123** [comment]
Thanks for the patch -- zip is not a problem though you can also create PRs on github.

"compiler/linker can create multiple copies of a const object"

Which compiler / linker are you using? And do you have any pointers to read about this behavior?

**Comment by lsh123** [comment]
>  I don't have any link to the GCC documentation...

I am just checking if there is something else going on. This explanation makes some sense, I am just not sure if this is indeed the full story.

**Comment by jmossber-vc** [comment]
Found this draft C standard online that you can read for free

https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf

...and it looks like your code is correct after all. From "6.2.4 Storage durations of objects"

```
The lifetime of an object is the portion of program execution during which storage is
guaranteed to be reserved for it. An object exists, has a constant address,33) and retains
its last-stored value throughout its lifetime.34)
``` 
```
33) The term ‘‘constant address’’ means that two pointers to the object constructed at possibly different
times will compare equal. The address may be different during two different executions of the same
program.
``` 
The problem must be on my side, maybe we have turn on some weird optimization flag, or I messed something up in my debugging. Sorry for the inconvenience. Closing the ticket.

**Comment by lsh123** [comment]
Thanks for digging into it. I will revert the patch for now but I am not opposed to this change (the only downside is changing the public header files :( ). 

Please let me know what you find -- I am curious.

**Comment by jmossber-vc** [comment]
I can no longer reproduce the problem, so the investigation has stalled.

**Comment by lsh123** [comment]
interesting, thanks for update. I will close this bug but please reopen if you see it again.
