### ISSUE TITLE
Testsuite fails with NSS 3.101 - keys too short

### ISSUE THREAD

**Issue by msirringhaus** [lsh123/xmlsec#806]
Starting with 3.101, NSS activated it's key size policy for all by default: https://hg.mozilla.org/projects/nss/diff/1c446939de6b34b57b7d1deab100d0579c5d1577/lib/nss/nssoptions.c

Leading to a number of failing tests in the testsuite, which apparently deal with shorter keys than what is now allowed. (gdb told me for one case e.g. 512 vs the allowed minimum of 1024).

If I revert this one change in NSS, xmlsec testsuite finishes without errors.

Not sure, if xmlsec should just deactivate these checks in NSS somehow when running the testsuite, or update all of its testsuite-keys to an appropriate length.

**Comment by lsh123** [comment]
The old tests are coming from the original (20+ years old) test vectors for XMLDsig / XMLEnc specs. I would love to keep them as-is. Let me see if there is a way to overwrite the key size policy for tests.

**Comment by lsh123** [comment]
I just downloaded the nss-3.102 from the mozilla website, built it, and run xmlsec against it -- all the tests passed. What OS are you using?

```
$ ldd ./apps/xmlsec1 
	linux-vdso.so.1 (0x00007fff6af11000)
	libnss3.so => /home/aleksey/local/nss-3.102/lib/libnss3.so (0x00007ce311600000)
	libnssutil3.so => /home/aleksey/local/nss-3.102/lib/libnssutil3.so (0x00007ce3115c1000)
	libsmime3.so => /home/aleksey/local/nss-3.102/lib/libsmime3.so (0x00007ce311589000)
...
``

**Comment by lsh123** [comment]
And also -- what tests are failing?

**Comment by msirringhaus** [comment]
Interesting. 
I'm testing on openSUSE. We are still using 1.2.38, but I did test also with the latest version. 

1.2.38:
[repo](https://build.opensuse.org/package/show/home:MSirringhaus:branches:LibreOffice:Factory/xmlsec1) and [buildlog](https://build.opensuse.org/build/home:MSirringhaus:branches:LibreOffice:Factory/openSUSE_Tumbleweed/x86_64/xmlsec1/_log)

1.3.4:
[repo](https://build.opensuse.org/package/show/home:MSirringhaus:branches:LibreOffice:Factory_new_version/xmlsec1) and [buildlog](https://build.opensuse.org/build/home:MSirringhaus:branches:LibreOffice:Factory_new_version/openSUSE_Tumbleweed/x86_64/xmlsec1/_log)

Maybe I have conflated those two failing versions, and both have a different root cause. 1.2.38 does have more failing tests.
I did test 1.2.38 with a modified NSS that rolled back the mentioned change, which made it build fine. I'll prepare 2 more repos tomorrow with both versions and a modified NSS, just to be sure.

**Comment by lsh123** [comment]
Any chance you can copy / paste logs?

" Anonymous user is not allowed here - please login (anonymous_user) "

(1.2.38 is indeed a bit old)

**Comment by msirringhaus** [comment]
Oh, sorry about that! I was under the impression that it would be open to everybody.

Failing:
[xmlsec-1.2.38.log](https://github.com/user-attachments/files/16172921/xmlsec-1.2.38.log)
[xmlsec-1.3.4.log](https://github.com/user-attachments/files/16172922/xmlsec-1.3.4.log)

After applying this patch to NSS, both version build and test fine.
```
Index: nss/lib/nss/nssoptions.c
===================================================================
--- nss.orig/lib/nss/nssoptions.c
+++ nss/lib/nss/nssoptions.c
@@ -40,7 +40,7 @@ static struct nssOps nss_ops = {
     0xffff,
     PR_FALSE,
     0,
-    NSS_KEY_SIZE_POLICY_ALL_FLAGS,
+    NSS_KEY_SIZE_POLICY_SSL_FLAG,
     SSL_ECC_MIN_CURVE_BITS
 };
```

**Comment by lsh123** [comment]
Thank you! Can you try the current master? I believe the only failing test on 1.3.4 was recently fixed (PR #804). I will take a look at 1.2.x branch -- it should be easy to fix if I can reproduce it.

**Comment by msirringhaus** [comment]
Yes, cherry-picking 804 on top of 1.3.4 does indeed fix the build! Thanks!
In case you can't reproduce, I can probably write out some short instructions on how to set up a container/distrobox for it, if you need it.

**Comment by lsh123** [comment]
Thanks, I was able to reproduce it and PR #811 should fix it. I also fixed a couple other things as well to make it work with latest NSS and LibXML2 so I will probably make a release shortly.

**Comment by lsh123** [comment]
This should have all the fixes: https://github.com/lsh123/xmlsec/discussions/818

**Comment by msirringhaus** [comment]
I can confirm that 1.2.40 is building fine now. Thank your very much, indeed!

**Comment by lsh123** [comment]
Thanks for bug report and testing!
