### ISSUE TITLE
xmlsec-nss: X509 possible certificate name error not checked; also, recommend Coverity Scan

### ISSUE THREAD

**Issue by cam888eron** [lsh123/xmlsec#82]
Hi, my name is Cameron MacMinn. I work at Cisco. We use XMLSec. We also use Coverity bug-finding tools.

Issue 1. Ran Coverity Connect on xmlsec1-1.2.23. Found 17 issues. This is 1st possible bug it found.

In xmlsec1-1.2.23/src/nss/x509vfy.c Coverity says:

   cond_notnull: Condition name != NULL, taking true branch. Now the value of name is not NULL.
358    xmlSecAssert2(name != NULL, NULL);
...
391    res = CERT_AsciiToName((char*)tmp);
   notnull: At condition name == NULL, the value of name cannot be NULL.
   dead_error_condition: The condition name == NULL cannot be true.
392    if (name == NULL) {
   CID 11233 (#1 of 1): Logically dead code (DEADCODE)dead_error_line: Execution cannot reach the expression xmlSecError inside this statement: xmlSecError("x509vfy.c", 39....
393        xmlSecError(XMLSEC_ERRORS_HERE,
...

Should this be?:
392    if (res == NULL) {

Re the other 16 issues, so far a few false positives. I will look at them as time permits, and be in touch if any more possible bugs.

----

Issue 2. I am very impressed with the Coverity tools. Also with Coverity Scan open source project.

I have joined the cURL and Jansson projects as a Coverity Scan observer. I plan to join more. When I tried to join XMLSec, I found out that your project is not a member.

I think your project would benefit. As far as I can tell, there is no cost. But it will take some time to keep track of it. In return, I expect you would get expert-level indications and some diagnosis of possible bugs in your code. I highly recommend it.

**Comment by lsh123** [comment]
1) It is already fixed:

https://github.com/lsh123/xmlsec/blob/master/src/nss/x509vfy.c#L391

2) Yes, we've had a discussion about it in the mailing list, I will do it in the near future.

**Comment by cam888eron** [comment]
Nice work. Thanks.
