### ISSUE TITLE
xmlsec: possible incorrect pointer dereference while writing namespace list for signature template

### ISSUE THREAD

**Issue by cam888eron** [lsh123/xmlsec#84]
Ran Coverity Connect on xmlsec1-1.2.23. Found possible incorrect pointer dereference while writing namespace list for signature template.

In xmlsec1-1.2.23/src/templates.c Coverity says:

    arith_non_null: The result of pointer arithmetic ++ptr is never null.
    notnull: At condition ++ptr == NULL, the value of ++ptr cannot be NULL.
    dead_error_condition: The condition ++ptr == NULL cannot be true.
2068        if((++ptr) == NULL) {
    CID 11193 (#1 of 1): Logically dead code (DEADCODE)dead_error_begin: Execution cannot reach this statement: xmlSecError("templates.c", ....
2069            xmlSecError(XMLSEC_ERRORS_HERE,
2070                        NULL,
2071                        NULL,
2072                        XMLSEC_ERRORS_R_INVALID_DATA,
2073                        "unexpected end of ns list");
2074            return(-1);
2075        }
2076        href = *(ptr++);

My (xmlsec1-1.2.23 release) #L2068 is your (github master) #L1714 . Looks like the intent of this line is to advance pointer to current href, and make sure it is present. Should this be?:
2068        if((*(++ptr)) == NULL) {

#L2076 looks correct, get current href and advance pointer to next prefix.

----

Also in same source file, possible typo in comment 3X my #L{1929,1975,2012} your #L{1581,1624,1662} 'information' not 'infromation' ? Ditto my #L2012 your #1662 'XPointer' not 'XPoniter' ?

**Comment by lsh123** [comment]
Yeah, fixed and made the code cleaner

https://github.com/lsh123/xmlsec/commit/dd7ed29879c06128ded287ab479e4d77eab06a9b

and typos too

https://github.com/lsh123/xmlsec/commit/25951dfd1a231c965ac6ac47d581704bc6931dd1
