### ISSUE TITLE
problem in signature verification

### ISSUE THREAD

**Issue by elvis-70** [lsh123/xmlsec#841]
Hello,

a message signed with canonicalization method

http://www.w3.org/2001/10/xml-exc-c14n#

is verified correctly,  while the same message signed with canonicalization

http://www.w3.org/TR/2001/REC-xml-c14n-20010315

fails verification.

Please find attached the two messages, the public certificate used and the xmlsec1 commands used.

Thank you for your help.

Regards,
Elvio

**Comment by lsh123** [comment]
Was the file signed by xmlsec? If yes then you can use `--store-references` parameter to see the canonicalized output right before digest is applied and compare those between signature and verification steps.

If this file was NOT signed by xmlsec, then you again can get the pre-digest output from xmlsec and compare it to the output from whatever software signed the file to see which one is producing wrong results.

**Comment by lsh123** [comment]
Oh... this brings memories :) This was discussed back in 2006-07 with Rich Saltz in xmlsec mailing list. Yes, this is most likely problem. IBM API gateway "fixed" this SAML spec problem by NOT following the C14N specs. Unfortunately there is no good solution for xmlsec except to use exc c14n (everything else will likely break someone else).

**Comment by elvis-70** [comment]
Ok, got it. We will try to make the issue fixed on the other (IBM) side.
Thank you (and your memories!) for the support.

Regards,
Elvio

**Comment by lsh123** [comment]
Rich *was* working at IBM on this API gateway at the time :) there is no good way to fix it. SAML spec + original C14N spec are just broken. Use Exc-C14N instead - it was literally invented to solve that problem with SAML.

**Comment by lsh123** [comment]
I am going to close this issue. I really don't have any good suggestions except use exc-c14n as I described above.

**Comment by elvis-70** [comment]
Ok, thank you for your help, we managed to change the XG45 configuration and things finally worked out.

Regards,

Elvio
