### ISSUE TITLE
v1.3.6 new test failures

### ISSUE THREAD

**Issue by andyrtr** [lsh123/xmlsec#847]
Arch linux package gives new test failures. OpenSSL is v3.3.2.
[xmlsec-1.3.6-1-x86_64-build.log](https://github.com/user-attachments/files/17511784/xmlsec-1.3.6-1-x86_64-build.log)
[xmlsec-1.3.6-1-x86_64-check.log](https://github.com/user-attachments/files/17511785/xmlsec-1.3.6-1-x86_64-check.log)

**Comment by lsh123** [comment]
The error `openssl error: error:1C8000AE:Provider routines::digest not allowed` on the `enveloped-ripemd160-ecdsa-ripemd160.tmpl` test indicates that RIPEMD160 is disabled on the OpenSSL Arch linux (no surprises here -- it's an old and not a very good digest by modern standards). Pass `--disable-ripemd160` to the xmlsec's `confgure` script to disable it in xmlsec too.

**Comment by andyrtr** [comment]
Thanks. This indeed fixes the tests.

**Comment by lsh123** [comment]
Just FYI, the RIPEMD160 will be disabled by default starting from the next release of xmlsec:

https://github.com/lsh123/xmlsec/commit/54570ea6042c4646bd468ad5c3520425c65ff3d9
