### ISSUE TITLE
xmlsec-openssl: possible weakness 2X in HMAC signature method due to unchecked error

### ISSUE THREAD

**Issue by cam888eron** [lsh123/xmlsec#85]
Ran Coverity Connect on xmlsec1-1.2.23. Found possible weakness 2X in Hash Message Authentication Code HMAC signature method due to unchecked error.

In xmlsec1-1.2.23/src/openssl/hmac.c Coverity says:

521            unsigned int dgstSize;
522
   CID 11190 (#1 of 1): Unchecked return value (CHECKED_RETURN)23. check_return: Calling HMAC_Final without checking return value (as is done elsewhere 19 out of 22 times).
523            HMAC_Final(ctx->hmacCtx, ctx->dgst, &dgstSize);
524            xmlSecAssert2(dgstSize > 0, -1);

In openssl/1.0.0k/crypto/hmac/hmac.c proc HMAC_Final() (not shown), code review finds 3X error returns before its len variable could be set. len there corresponds to unititialized variable dgstSize here. Looks like code here has a good chance of apparently succeeding, despite earlier error in HMAC_Final().

Better to check for HMAC_Final() error after my #L523, your #L490 ?

----

Also in same source file:

   CID 11171 (#1 of 1): Unchecked return value (CHECKED_RETURN)21. check_return: Calling HMAC_Update without checking return value (as is done elsewhere 32 out of 40 times).
507            HMAC_Update(ctx->hmacCtx, xmlSecBufferGetData(in), inSize);

Possibly less concern, but good practice to check for error after my #L507, your #L476 ?

----

Also from code review in same source file:

Possible typo #L14 'precise' not 'preciese' ?

**Comment by lsh123** [comment]
old openssl didn't return anything (https://www.openssl.org/docs/man1.1.0/crypto/HMAC_Update.html). fixed
