### ISSUE TITLE
Question: What typically caused "unable to get local issuer certificate" out of no where?

### ISSUE THREAD

**Issue by totszwai** [lsh123/xmlsec#850]
Hello,

We have been using xmlsec for a long while and recerntly updated to `1.2.41`, **everything seems to be working fine up until last week or so**, however today, all of a sudden, we are unable to verify digital signatures from XML...

At first we thought maybe some root certificates or intermediate CAs were expired in Windows, we checked it to ensure everything is fine but then the same thing happened in Ubuntu as well... we then tried to run the old version of our software (something that was over a year old) which uses `1.2.38` and is the same thing. `unable to get local issuer certificate`.

Do you know what could cause such weird behavior? The below error happened in both Windows and Linux:

```
Reason: certificate verification failed (71)
X509_verify_cert: subject=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=TEST baCA1
 issuer=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=baRCA1
 err=20
 msg=unable to get local issuer certificate
 Error: xmlSecOpenSSLX509StoreVerify (x509vfy.c:435) x509-store
Reason: certificate verification failed (71)
subject=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=TEST baCA1
 issuer=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=baRCA1
 err=20
 msg=unable to get local issuer certificate
 Error: xmlSecKeysMngrGetKey (keys.c:1256)  xmlSecKeysMngrFindKey
Reason: xmlsec library function failed (1)
 Error: xmlSecDSigCtxProcessKeyInfoNode (xmldsig.c:800)
Reason: key is not found (45)
details=NULL
 Error: xmlSecDSigCtxProcessSignatureNode (xmldsig.c:514)  xmlSecDSigCtxProcessKeyInfoNode
Reason: xmlsec library function failed (1)
 Error: xmlSecDSigCtxVerify (xmldsig.c:352)  xmlSecDSigCtxProcessSignatureNode
Reason: xmlsec library function failed (1)
```

This is from the older `1.2.38` which I haven't format the output to be more developer friendly back then.
```
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=389:obj=x509-store:subj=unknown:error=71:certificate verification failed:X509_verify_cert: subject=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=TEST Signing CA1; issuer=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=TEST cisRCA1; err=20; msg=unable to get local issuer certificate
func=xmlSecOpenSSLX509StoreVerify:file=x509vfy.c:line=432:obj=x509-store:subj=unknown:error=71:certificate verification failed:subject=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=TEST Signing CA1; issuer=/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=TEST cisRCA1; err=20; msg=unable to get local issuer certificate
func=xmlSecKeysMngrGetKey:file=keys.c:line=1256:obj=unknown:subj=xmlSecKeysMngrFindKey:error=1:xmlsec library function failed:
func=xmlSecDSigCtxProcessKeyInfoNode:file=xmldsig.c:line=800:obj=unknown:subj=unknown:error=45:key is not found:details=NULL
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=514:obj=unknown:subj=xmlSecDSigCtxProcessKeyInfoNode:error=1:xmlsec library function failed:
func=xmlSecDSigCtxVerify:file=xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed:
```

It would make sense it it fail with our new code using the `1.2.41` but even the old stuff that was working is suddenly throwing the same behavior, which makes me think that the problem is else where... however I have no idea where!

Could the xmlsec God give some guidance on this? T_T

Regards,

**Comment by lsh123** [comment]
The error you get:

> unable to get local issuer certificate

indicates that XMLSec can't find the `/C=CA/O=Some Company/OU=TEST Certification Authorities/CN=baRCA1 `certificate in the chain (e.g. it cannot find root/CA certificate). There are two options here:

1/ This certificate expired.
2/ The OpenSSL configuration changed.

If you are using xmlsec command line utility, then start from checking that all files / folders in the command line are correct. Then check if OpenSSL configuration file (default location varies by system) changed and if all the locations there are correct.

If you are using xmlsec library, then again check OpenSSL configs and your code that configures certificates store, etc.

**Comment by totszwai** [comment]
The certificate is indeed expired, but has this behavior of not fetching/finding the certificate when is expired changed? Can't I still verify the digital signature anyway despite the certificate within the XML expired? The signature itself should/would still be valid since there is a timestamp for the signature.

Does it still matter/relate to OpenSSL though, if I am pulling the signature certificate off the XML document?

Thank you for your fast reply!!!

**Comment by lsh123** [comment]
This question goes very deep into the discussion of PKI / certificates and what does it mean for certificate / signature to be valid. For practical purposes, xmlsec provides a way to verify that a signature was valid at a given time (see `--verification-time` option for xmlsec command line utility and similar flag on `xmlSecDSigCtx`)

BTW, XML Enc spec provides an option of fetching key "at runtime" (and xmlsec supports it for both signatures and encryption):

https://www.w3.org/TR/xmlenc-core1/#sec-ds-RetrievalMethod

This was designed to exactly solve the problem you are describing. Said that, I haven't seen a single production use of `RetrievalMethod` in 10 years since it was introduced :)

**Comment by totszwai** [comment]
We are using the `certsVerificationTime` property when timestamp is presented.

```
        // we also have our option to skip checking the certificate too
        // but we REALLY don't want to set this flag
        if (opts & VERIFY_DONT_VERIFY_CERTS)
            dsigctx->keyInfoReadCtx.flags |= XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS;

        if (timestamp)
            dsigctx->keyInfoReadCtx.certsVerificationTime = timestamp;
```

Despite passing the timestamp, it looks like xmlsec is still throwing the same error:

> unable to get local issuer certificate

Is that the expected behavior? This is in the `1.2.41` and I am passing the `verificationTime`

![image](https://github.com/user-attachments/assets/cd04857d-ab4d-4cf1-baad-4d3ccec1f6ee)
https://github.com/lsh123/xmlsec/blob/xmlsec-1_2_41/src/openssl/x509vfy.c#L336


![image](https://github.com/user-attachments/assets/5c99d2ea-958f-489c-aef6-010f385cb4b0)
https://github.com/lsh123/xmlsec/blob/xmlsec-1_2_41/src/openssl/x509vfy.c#L353

**Comment by totszwai** [comment]
There might be a bug of it not using the correct context when checking the cert?
When I debug the code, we could see that xmlsec attempted to set the `vpm`
https://github.com/lsh123/xmlsec/blob/xmlsec-1_2_41/src/openssl/x509vfy.c#L360

However, on the context side of things, the `check_time` is still `0`:
![image](https://github.com/user-attachments/assets/7dae5516-4841-49fd-ad52-5d3cb47c8672)

It is being set inide the certificate context though:
![image](https://github.com/user-attachments/assets/3394182d-09ea-424c-b282-1faf2c06d44b)

**Comment by lsh123** [comment]
I see that you are also using `XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS` which is pretty dangerous. I would not recommend to use it in production.

Regardless, if you can reproduce the problem with xmlsec and then share the test case (file, certs) then I would be happy to take a look. There are test cases in the xmlsec test suite to check for this. It's hard to debug it with screenshots.

BTW, I don't think it matters for this specific case, but I would recommend to upgrade to 1.3.x -- there are quite a few performance improvements that you might benefit from.

**Comment by totszwai** [comment]
Apologies, the root cause, was actually due to the trustanchors that we pass to xmlsec via `xmlSecCryptoAppKeysMngrCertLoadMemory` don't actually chain to the cert that we are trying to validate...

Since I am NOT quite fluent with xmlsec and crypto stuff, it was difficult for me to trace back to the root cause... also the error messages from xmlsec wasn't quite user friendly/helpful either (lol)


Regarding upgrading to 1.3.x, can we still use it if we are currently stuck with openssl 1.x?

Thank you so much for your help and time!!!!

**Comment by lsh123** [comment]
> Regarding upgrading to 1.3.x, can we still use it if we are currently stuck with openssl 1.x?

Yes, OpenSSL 1.1.x is fully supported and every single change is tested against it. For example the latest commit to master:

https://github.com/lsh123/xmlsec/actions/runs/11543377059/job/32127686401
