### ISSUE TITLE
func=xmlSecDSigCtxProcessSignatureNode:file=..\src\xmldsig.c:line=442:obj=unknown:subj=dsigCtx->signValueNode == NULL:error=100:assertion:  func=xmlSecDSigCtxVerify:file=..\src\xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 

### ISSUE THREAD

**Issue by arunkumarvn** [lsh123/xmlsec#857]
Hi Team,

I am using verify1.c to verify the xml digital signature using public_key.pem and Signature_File.xml. But I am facing an issue from long time.  

_**func=xmlSecDSigCtxProcessSignatureNode:file=..\src\xmldsig.c:line=442:obj=unknown:subj=dsigCtx->signValueNode == NULL:error=100:assertion: 
func=xmlSecDSigCtxVerify:file=..\src\xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature verification failed**_

When i tried same PEM and XML file in Linux with XMLSEC1 command. It's working as expected. 

So, i thought the SSL key is not helping to parse and get node properly. So, i tried to convert SSL key to XMLSEC Key. But i am getting the API's are not available in library. 

    // Create the xmlSec key (use xmlSecOpenSSLKeyData or similar function depending on XMLSec version)
    xmlSecKeyPtr xmlSecKey = xmlSecOpenSSLKeyDataCreate();

    // Create an OpenSSL Key Data object using the EVP_PKEY
    xmlSecKeyDataPtr keyData = xmlSecOpenSSLKeyDataCreate();

    // Set the EVP_PKEY in the xmlSecKeyData object
    int result = xmlSecOpenSSLKeyDataSetKey(keyData, evpKey);

    // Set the key data in the xmlSecKey
    xmlSecKeySetData(xmlSecKey, keyData);

All these APIs are showing UNDECLARED IDENTIFIER. I have searched in entire library as well. But it is not there. Could you please support here to convert SSL KEY to XMLSEC KEY to verify the XML File using Verify1.c

Thanks,
Arunkumar

**Comment by lsh123** [comment]
If xmlsec command line utility works fine, then it looks like a problem with your build. I would start from building xmlsec and examples with static linking to avoid any issues with loading wrong version of shared libraries.

**Comment by arunkumarvn** [comment]
I have downloaded binaries from XMLSEC website https://www.aleksey.com/xmlsec/download/win64/xmlsec1-1.2.38-win64.zip and https://www.aleksey.com/xmlsec/download/win64/xmlsec1-1.3.6-win64.zip. 

Both I have verified. But issues are same, it throws same error.

**Comment by lsh123** [comment]
I bet you have wrong runtimes:

https://github.com/lsh123/xmlsec/tree/master/win32

Again, if xmlsec command line tool works and the code you compiled doesn't -- something is wrong with your compilation/ build / ...

**Comment by arunkumarvn** [comment]
Thanks for the quick response.

As i mentioned in the first post. I am trying to run in command line on Linux Platform (Ubuntu). There i have installed xmlsec1 via command line **apt-get install xmlsec1**. There it was worked fine. 

But if i try to compile in windows 11, issues were raised. So, i have downloaded the same libraries provided in the XMLSEC GIT #@https://www.aleksey.com/xmlsec/download/win64/xmlsec1-1.2.38-win64.zip. Still got same issues.

So, I have compiled the library in Linux (Ubuntu). It's compiled successfully with OPENSSL. Then i took verify1.c and compiled using the library. But i am getting the below variables are not available, i have added all the required headers.

```
// Create the xmlSec key (use xmlSecOpenSSLKeyData or similar function depending on XMLSec version)
xmlSecKeyPtr xmlSecKey = xmlSecOpenSSLKeyDataCreate();

// Create an OpenSSL Key Data object using the EVP_PKEY
xmlSecKeyDataPtr keyData = xmlSecOpenSSLKeyDataCreate();

// Set the EVP_PKEY in the xmlSecKeyData object
int result = xmlSecOpenSSLKeyDataSetKey(keyData, evpKey);

// Set the key data in the xmlSecKey
xmlSecKeySetData(xmlSecKey, keyData); 
```

Could you please help me to resolve the issues raised to convert SSL Key to XMLSEC Key.

**Comment by arunkumarvn** [comment]
Please find the signature. It looks like below in the XML File . This is signed using DOTNET XML DIGITAL SIGNATURE.

```
<Licence>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>hh/Dz1kBfGfBKvrTtCjxUOk0AX0=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>N436SyVgv+VtezHJFHjP501Ls9zAJ66ye9p5WCaUCvtphhH21pu6TyrWYwbNi/6INuaYeVv68ZM2/W78uoR7YOeV+fvJGxyAh0etUnqdRN/i/zu1DEC90QUFLOrAbW8VyYMSJv1hxEoOmw0sdA8EIyOk1GxM/+est77w18wNJk8=</SignatureValue>
</Signature>
</Licence>
```

I am trying to verify from the XMLSEC Library using verify1.c code

**Comment by lsh123** [comment]
If you can reproduce the problem using the xmlsec command line tool then I will be happy to take a look. Unfortunately, I cannot debug the code that I didn't write.

**Comment by arunkumarvn** [comment]
I am using the same https://github.com/lsh123/xmlsec/blob/master/examples/verify1.c example code provided in the GITHUB. This is showing the result like below.
```
func=xmlSecDSigCtxProcessSignatureNode:file=..\src\xmldsig.c:line=442:obj=unknown:subj=dsigCtx->signValueNode == NULL:error=100:assertion: 
func=xmlSecDSigCtxVerify:file=..\src\xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature verification failed
Signature verification failed!
```

Same License File and Same Public Key shows valid in the Command Line Tool on Ubuntu (XMLSEC1).
```
xmlsec1 --verify --pubkey-pem publicekey.pem License.xml
OK
SignedInfo References (ok/all): 1/1
Manifests References (ok/all): 0/0 
```

**Comment by lsh123** [comment]
As I mentioned above, you have a problem with how you build the example. The error ``dsigCtx->signValueNode == NULL`` indicates that internal structures are messed up between compilation and execution:
1/ Example is compiled with different flags than core xmlsec library
2/ Example is using different version of xmlsec library at runtime vs at compile time
3/ (windows) Example is compiled with different MSVC runtime libraries than the xmlsec library

**Comment by arunkumarvn** [comment]
Instead of windows MSVC. I have tried to compile the library using the default flags and default commands.

```
./autogen.sh
./configure
make
make install
```

Compiled example code using same gcc https://github.com/lsh123/xmlsec/blob/master/examples/verify1.c. After that also, i am getting same issue. 
```
func=xmlSecDSigCtxProcessSignatureNode:file=..\src\xmldsig.c:line=442:obj=unknown:subj=dsigCtx->signValueNode == NULL:error=100:assertion: 
func=xmlSecDSigCtxVerify:file=..\src\xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed: 
Error: signature verification failed
Signature verification failed!

```

**Comment by lsh123** [comment]
Sorry missed your comment:
1/ Build static linking:  `./configure --enable-static --enable-static-linking`
2/ After you compile example, check which libraries is it loaded: `ldd verify1`

**Comment by arunkumarvn** [comment]
i did modification to code and tried to run with modifications and verified `ldd appname` 
tried to verify signature using https://www.aleksey.com/xmlsec/api/xmlsec-notes-verify.html 
But i got some compilation issues for xmlSecCryptoAppKeyLoad so i used xmlSecOpenSSLAppKeyLoad. 
After that code compiled successfully. But i am facing issues at last to verify signature and it is saying dsigctx->signvalueNode == NULL. 

I have tried to use root node as well. But both got null only. 
`xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:Line=442:obj=unknown:subj=dsigCtx->signValueNode == NULL : error 100: assertion: func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=352:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed`

**Note:**I have defined XMLSEC_CRYPTO_OPENSSL to access openSSL headers in Library. 
Is there any way to resolve issue by using xmlSecOpenSSLAppKeyLoad or any other need to change to see why I am getting NULL ? What is expected behavior? 

Could you provide information on what will be the expected data for **node** in the `xmlSecDsigCtxVerify(dsigCtx, node)`

**Comment by lsh123** [comment]
No it's not correct. As I mentioned before, I suspect mismatch between headers during compilation and libraries at runtime. But I can't debug or help you any further since this issue is not reproducible with xmlsec command line tool.

**Comment by lsh123** [comment]
Please reopen if you still have a problem and if you can reproduce it with xmlsec command line tool.
