### ISSUE TITLE
xmlsec: possible weak cryptography in XML unique ID

### ISSUE THREAD

**Issue by cam888eron** [lsh123/xmlsec#86]
Ran Coverity Connect on xmlsec1-1.2.23. Found possible weak cryptography in XML unique ID.

In xmlsec1-1.2.23/src/xmltree.c Coverity says:

   CID 11230 (#1 of 1): Don't call (DC.WEAK_CRYPTO)dont_call: rand() should not be used for security related applications, as linear congruential algorithms are too easy to break.
    Use /dev/random or /dev/urandom instead.
 863        (xmlSecBufferGetData(&buffer)) [i] = (xmlSecByte) (256.0 * rand() / (RAND_MAX + 1.0));

This proc appears to be for clients, XMLSec itself not so much. Any security concerns?

**Comment by lsh123** [comment]
These two functions are not really used in the code anymore, marked obsolete and will remove in +2 release. Will keep the issue open for now.

**Comment by lsh123** [comment]
Removed in https://github.com/lsh123/xmlsec/pull/105
