### ISSUE TITLE
xmlsec: possible missing error check

### ISSUE THREAD

**Issue by cam888eron** [lsh123/xmlsec#87]
Ran Coverity Connect on xmlsec1-1.2.23. This is the last issue which it found, possible missing error check.

In xmlsec1-1.2.23/src/nodeset.c Coverity says:

   CID 11180 (#1 of 1): Unchecked return value (CHECKED_RETURN)5. check_return: Calling xmlOutputBufferWriteString without checking return value (as is done elsewhere 11 out of 12 times).
520        xmlOutputBufferWriteString((xmlOutputBufferPtr)data,
521                                    (char*)(cur->content));

In xmlsec1-1.2.23/src/relationship.c (not shown), code review finds that error is checked for after every xmlOutputBufferWriteString() call.

Better to check for error after my #L520, your #L500 ?

**Comment by lsh123** [comment]
fixed https://github.com/lsh123/xmlsec/pull/97
